# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCharts import QChartView
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGridLayout, QHBoxLayout,
    QLabel, QLayout, QLineEdit, QPushButton,
    QSizePolicy, QSpacerItem, QStackedWidget, QTextEdit,
    QVBoxLayout, QWidget)
from icons import Icons_rc

class Ui_Main(object):
    def setupUi(self, Main):
        if not Main.objectName():
            Main.setObjectName(u"Main")
        Main.resize(1024, 600)
        Main.setMinimumSize(QSize(1024, 600))
        Main.setMaximumSize(QSize(1024, 600))
        self.Menu = QFrame(Main)
        self.Menu.setObjectName(u"Menu")
        self.Menu.setEnabled(True)
        self.Menu.setGeometry(QRect(0, 0, 1024, 75))
        self.Menu.setMinimumSize(QSize(0, 75))
        self.Menu.setMaximumSize(QSize(16777215, 75))
        self.Menu.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.0113636 rgba(225, 225, 225, 255), stop:1 rgba(245, 245, 245, 255));")
        self.Menu.setFrameShape(QFrame.NoFrame)
        self.Menu.setFrameShadow(QFrame.Raised)
        self.horizontalLayoutWidget = QWidget(self.Menu)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(0, 0, 1031, 81))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(20, 5, 20, 10)
        self.btn_Measure = QPushButton(self.horizontalLayoutWidget)
        self.btn_Measure.setObjectName(u"btn_Measure")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Measure.sizePolicy().hasHeightForWidth())
        self.btn_Measure.setSizePolicy(sizePolicy)
        self.btn_Measure.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_Measure.setAcceptDrops(False)
        self.btn_Measure.setAutoFillBackground(False)
        self.btn_Measure.setStyleSheet(u"border-bottom-color: rgb(255, 85, 0);")
        icon = QIcon()
        icon.addFile(u":/Menu/menu/Measure.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Measure.setIcon(icon)
        self.btn_Measure.setIconSize(QSize(48, 48))
        self.btn_Measure.setCheckable(True)
        self.btn_Measure.setChecked(True)
        self.btn_Measure.setAutoRepeat(False)
        self.btn_Measure.setAutoExclusive(True)
        self.btn_Measure.setAutoDefault(False)
        self.btn_Measure.setFlat(True)

        self.horizontalLayout.addWidget(self.btn_Measure)

        self.btn_Graphs = QPushButton(self.horizontalLayoutWidget)
        self.btn_Graphs.setObjectName(u"btn_Graphs")
        sizePolicy.setHeightForWidth(self.btn_Graphs.sizePolicy().hasHeightForWidth())
        self.btn_Graphs.setSizePolicy(sizePolicy)
        self.btn_Graphs.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_Graphs.setAcceptDrops(False)
        self.btn_Graphs.setAutoFillBackground(False)
        self.btn_Graphs.setStyleSheet(u"border-bottom-color: rgb(255, 85, 0);")
        icon1 = QIcon()
        icon1.addFile(u":/Menu/menu/Graph.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Graphs.setIcon(icon1)
        self.btn_Graphs.setIconSize(QSize(48, 48))
        self.btn_Graphs.setCheckable(True)
        self.btn_Graphs.setChecked(False)
        self.btn_Graphs.setAutoRepeat(False)
        self.btn_Graphs.setAutoExclusive(True)
        self.btn_Graphs.setAutoDefault(False)
        self.btn_Graphs.setFlat(True)

        self.horizontalLayout.addWidget(self.btn_Graphs)

        self.btn_Settings = QPushButton(self.horizontalLayoutWidget)
        self.btn_Settings.setObjectName(u"btn_Settings")
        sizePolicy.setHeightForWidth(self.btn_Settings.sizePolicy().hasHeightForWidth())
        self.btn_Settings.setSizePolicy(sizePolicy)
        self.btn_Settings.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_Settings.setAcceptDrops(False)
        self.btn_Settings.setAutoFillBackground(False)
        self.btn_Settings.setStyleSheet(u"border-bottom-color: rgb(255, 85, 0);")
        icon2 = QIcon()
        icon2.addFile(u":/Menu/menu/Settings.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Settings.setIcon(icon2)
        self.btn_Settings.setIconSize(QSize(48, 48))
        self.btn_Settings.setCheckable(True)
        self.btn_Settings.setChecked(False)
        self.btn_Settings.setAutoRepeat(False)
        self.btn_Settings.setAutoExclusive(True)
        self.btn_Settings.setAutoDefault(False)
        self.btn_Settings.setFlat(True)

        self.horizontalLayout.addWidget(self.btn_Settings)

        self.btn_Errors = QPushButton(self.horizontalLayoutWidget)
        self.btn_Errors.setObjectName(u"btn_Errors")
        sizePolicy.setHeightForWidth(self.btn_Errors.sizePolicy().hasHeightForWidth())
        self.btn_Errors.setSizePolicy(sizePolicy)
        self.btn_Errors.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_Errors.setAcceptDrops(False)
        self.btn_Errors.setAutoFillBackground(False)
        self.btn_Errors.setStyleSheet(u"border-bottom-color: rgb(255, 85, 0);")
        icon3 = QIcon()
        icon3.addFile(u":/Menu/menu/Error.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Errors.setIcon(icon3)
        self.btn_Errors.setIconSize(QSize(48, 48))
        self.btn_Errors.setCheckable(True)
        self.btn_Errors.setChecked(False)
        self.btn_Errors.setAutoRepeat(False)
        self.btn_Errors.setAutoExclusive(True)
        self.btn_Errors.setAutoDefault(False)
        self.btn_Errors.setFlat(True)

        self.horizontalLayout.addWidget(self.btn_Errors)

        self.Content = QFrame(Main)
        self.Content.setObjectName(u"Content")
        self.Content.setGeometry(QRect(0, 75, 1024, 525))
        font = QFont()
        font.setFamilies([u"Futura Std Book"])
        self.Content.setFont(font)
        self.Content.setStyleSheet(u"")
        self.Content.setFrameShape(QFrame.NoFrame)
        self.Content.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.Content)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.Screen = QStackedWidget(self.Content)
        self.Screen.setObjectName(u"Screen")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.Screen.sizePolicy().hasHeightForWidth())
        self.Screen.setSizePolicy(sizePolicy1)
        self.Screen_Logo = QWidget()
        self.Screen_Logo.setObjectName(u"Screen_Logo")
        self.horizontalLayoutWidget_2 = QWidget(self.Screen_Logo)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(0, -69, 1031, 601))
        self.horizontalLayout_3 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(50, 50, 50, 100)
        self.logo_Polsl = QLabel(self.horizontalLayoutWidget_2)
        self.logo_Polsl.setObjectName(u"logo_Polsl")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.logo_Polsl.sizePolicy().hasHeightForWidth())
        self.logo_Polsl.setSizePolicy(sizePolicy2)
        self.logo_Polsl.setMinimumSize(QSize(250, 250))
        self.logo_Polsl.setMaximumSize(QSize(250, 250))
        self.logo_Polsl.setBaseSize(QSize(478, 700))
        self.logo_Polsl.setPixmap(QPixmap(u":/Logo/logo/polsl.png"))
        self.logo_Polsl.setScaledContents(True)
        self.logo_Polsl.setWordWrap(False)

        self.horizontalLayout_3.addWidget(self.logo_Polsl)

        self.logoMt = QLabel(self.horizontalLayoutWidget_2)
        self.logoMt.setObjectName(u"logoMt")
        sizePolicy2.setHeightForWidth(self.logoMt.sizePolicy().hasHeightForWidth())
        self.logoMt.setSizePolicy(sizePolicy2)
        self.logoMt.setMinimumSize(QSize(250, 250))
        self.logoMt.setMaximumSize(QSize(250, 250))
        self.logoMt.setBaseSize(QSize(478, 700))
        self.logoMt.setPixmap(QPixmap(u":/Logo/logo/mt.png"))
        self.logoMt.setScaledContents(True)
        self.logoMt.setWordWrap(False)

        self.horizontalLayout_3.addWidget(self.logoMt)

        self.Screen.addWidget(self.Screen_Logo)
        self.Screen_MeasureMain = QWidget()
        self.Screen_MeasureMain.setObjectName(u"Screen_MeasureMain")
        self.title_MeasureMain = QLabel(self.Screen_MeasureMain)
        self.title_MeasureMain.setObjectName(u"title_MeasureMain")
        self.title_MeasureMain.setGeometry(QRect(50, 30, 181, 71))
        font1 = QFont()
        font1.setFamilies([u"Futura Std Book"])
        font1.setPointSize(36)
        self.title_MeasureMain.setFont(font1)
        self.title_MeasureMain.setTextFormat(Qt.AutoText)
        self.title_MeasureMain.setScaledContents(False)
        self.title_MeasureMain.setWordWrap(False)
        self.title_MeasureMain.setIndent(-1)
        self.btn_StartMeasure = QPushButton(self.Screen_MeasureMain)
        self.btn_StartMeasure.setObjectName(u"btn_StartMeasure")
        self.btn_StartMeasure.setGeometry(QRect(360, 210, 281, 91))
        font2 = QFont()
        font2.setFamilies([u"Futura Std Book"])
        font2.setPointSize(24)
        self.btn_StartMeasure.setFont(font2)
        self.btn_StartMeasure.setStyleSheet(u"background-color: rgb(191, 191, 191);")
        self.btn_MeasureToGraph = QPushButton(self.Screen_MeasureMain)
        self.btn_MeasureToGraph.setObjectName(u"btn_MeasureToGraph")
        self.btn_MeasureToGraph.setGeometry(QRect(250, 320, 531, 91))
        self.btn_MeasureToGraph.setFont(font2)
        self.btn_MeasureToGraph.setAutoFillBackground(False)
        self.btn_MeasureToGraph.setStyleSheet(u"background-color: rgb(191, 191, 191);")
        self.btn_MeasureToGraph.setAutoRepeat(False)
        self.Screen.addWidget(self.Screen_MeasureMain)
        self.Screen_MeasureProgress = QWidget()
        self.Screen_MeasureProgress.setObjectName(u"Screen_MeasureProgress")
        self.btn_StopMeasure = QPushButton(self.Screen_MeasureProgress)
        self.btn_StopMeasure.setObjectName(u"btn_StopMeasure")
        self.btn_StopMeasure.setGeometry(QRect(730, 90, 261, 61))
        self.btn_StopMeasure.setFont(font2)
        self.btn_StopMeasure.setStyleSheet(u"background-color: rgb(191, 191, 191);")
        self.stackedWidget = QStackedWidget(self.Screen_MeasureProgress)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(3, 0, 1021, 521))
        self.SubScreen_Measure_Step1 = QWidget()
        self.SubScreen_Measure_Step1.setObjectName(u"SubScreen_Measure_Step1")
        self.title_MeasureProgress = QLabel(self.SubScreen_Measure_Step1)
        self.title_MeasureProgress.setObjectName(u"title_MeasureProgress")
        self.title_MeasureProgress.setGeometry(QRect(120, 50, 491, 71))
        self.title_MeasureProgress.setFont(font1)
        self.title_MeasureProgress.setTextFormat(Qt.AutoText)
        self.title_MeasureProgress.setScaledContents(False)
        self.title_MeasureProgress.setWordWrap(False)
        self.title_MeasureProgress.setIndent(-1)
        self.text_MeasureProgress_Step1_1 = QLabel(self.SubScreen_Measure_Step1)
        self.text_MeasureProgress_Step1_1.setObjectName(u"text_MeasureProgress_Step1_1")
        self.text_MeasureProgress_Step1_1.setGeometry(QRect(40, 170, 661, 271))
        font3 = QFont()
        font3.setFamilies([u"Futura Std Book"])
        font3.setPointSize(20)
        self.text_MeasureProgress_Step1_1.setFont(font3)
        self.text_MeasureProgress_Step1_1.setFrameShape(QFrame.Box)
        self.text_MeasureProgress_Step1_1.setFrameShadow(QFrame.Sunken)
        self.text_MeasureProgress_Step1_1.setTextFormat(Qt.AutoText)
        self.text_MeasureProgress_Step1_1.setScaledContents(False)
        self.text_MeasureProgress_Step1_1.setAlignment(Qt.AlignCenter)
        self.text_MeasureProgress_Step1_1.setWordWrap(False)
        self.text_MeasureProgress_Step1_1.setIndent(-1)
        self.Btn_MeasureProgress_Step1_ObjectReady = QPushButton(self.SubScreen_Measure_Step1)
        self.Btn_MeasureProgress_Step1_ObjectReady.setObjectName(u"Btn_MeasureProgress_Step1_ObjectReady")
        self.Btn_MeasureProgress_Step1_ObjectReady.setGeometry(QRect(760, 240, 200, 200))
        self.Btn_MeasureProgress_Step1_ObjectReady.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.Btn_MeasureProgress_Step1_ObjectReady.setLayoutDirection(Qt.LeftToRight)
        icon4 = QIcon()
        icon4.addFile(u":/Progress/progress/Checkmark.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.Btn_MeasureProgress_Step1_ObjectReady.setIcon(icon4)
        self.Btn_MeasureProgress_Step1_ObjectReady.setIconSize(QSize(128, 128))
        self.Btn_MeasureProgress_Step1_ObjectReady.setFlat(False)
        self.text_MeasureProgress_Step1_2 = QLabel(self.SubScreen_Measure_Step1)
        self.text_MeasureProgress_Step1_2.setObjectName(u"text_MeasureProgress_Step1_2")
        self.text_MeasureProgress_Step1_2.setGeometry(QRect(816, 380, 91, 71))
        self.text_MeasureProgress_Step1_2.setFont(font3)
        self.text_MeasureProgress_Step1_2.setTextFormat(Qt.AutoText)
        self.text_MeasureProgress_Step1_2.setScaledContents(False)
        self.text_MeasureProgress_Step1_2.setWordWrap(False)
        self.text_MeasureProgress_Step1_2.setIndent(-1)
        self.stackedWidget.addWidget(self.SubScreen_Measure_Step1)
        self.SubScreen_Measure_Step2 = QWidget()
        self.SubScreen_Measure_Step2.setObjectName(u"SubScreen_Measure_Step2")
        self.stackedWidget.addWidget(self.SubScreen_Measure_Step2)
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QWidget()
        self.page_6.setObjectName(u"page_6")
        self.stackedWidget.addWidget(self.page_6)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayoutWidget_3 = QWidget(self.Screen_MeasureProgress)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(730, 20, 260, 58))
        self.horizontalLayout_5 = QHBoxLayout(self.verticalLayoutWidget_3)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.Dsp_MeasureProgress_Step_4 = QPushButton(self.verticalLayoutWidget_3)
        self.Dsp_MeasureProgress_Step_4.setObjectName(u"Dsp_MeasureProgress_Step_4")
        self.Dsp_MeasureProgress_Step_4.setEnabled(False)
        icon5 = QIcon()
        icon5.addFile(u":/Progress/progress/Empty.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon5.addFile(u":/Progress/progress/True.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        icon5.addFile(u":/Progress/progress/Empty.png", QSize(), QIcon.Mode.Disabled, QIcon.State.Off)
        icon5.addFile(u":/Progress/progress/True.png", QSize(), QIcon.Mode.Disabled, QIcon.State.On)
        self.Dsp_MeasureProgress_Step_4.setIcon(icon5)
        self.Dsp_MeasureProgress_Step_4.setIconSize(QSize(48, 48))
        self.Dsp_MeasureProgress_Step_4.setFlat(True)

        self.horizontalLayout_5.addWidget(self.Dsp_MeasureProgress_Step_4)

        self.Dsp_MeasureProgress_Step_3 = QPushButton(self.verticalLayoutWidget_3)
        self.Dsp_MeasureProgress_Step_3.setObjectName(u"Dsp_MeasureProgress_Step_3")
        self.Dsp_MeasureProgress_Step_3.setEnabled(False)
        self.Dsp_MeasureProgress_Step_3.setIcon(icon5)
        self.Dsp_MeasureProgress_Step_3.setIconSize(QSize(48, 48))
        self.Dsp_MeasureProgress_Step_3.setFlat(True)

        self.horizontalLayout_5.addWidget(self.Dsp_MeasureProgress_Step_3)

        self.Dsp_MeasureProgress_Step_2 = QPushButton(self.verticalLayoutWidget_3)
        self.Dsp_MeasureProgress_Step_2.setObjectName(u"Dsp_MeasureProgress_Step_2")
        self.Dsp_MeasureProgress_Step_2.setEnabled(False)
        self.Dsp_MeasureProgress_Step_2.setIcon(icon5)
        self.Dsp_MeasureProgress_Step_2.setIconSize(QSize(48, 48))
        self.Dsp_MeasureProgress_Step_2.setFlat(True)

        self.horizontalLayout_5.addWidget(self.Dsp_MeasureProgress_Step_2)

        self.Dsp_MeasureProgress_Step_1 = QPushButton(self.verticalLayoutWidget_3)
        self.Dsp_MeasureProgress_Step_1.setObjectName(u"Dsp_MeasureProgress_Step_1")
        self.Dsp_MeasureProgress_Step_1.setEnabled(False)
        self.Dsp_MeasureProgress_Step_1.setIcon(icon5)
        self.Dsp_MeasureProgress_Step_1.setIconSize(QSize(48, 48))
        self.Dsp_MeasureProgress_Step_1.setFlat(True)

        self.horizontalLayout_5.addWidget(self.Dsp_MeasureProgress_Step_1)

        self.Screen.addWidget(self.Screen_MeasureProgress)
        self.stackedWidget.raise_()
        self.btn_StopMeasure.raise_()
        self.verticalLayoutWidget_3.raise_()
        self.Screen_Graphs = QWidget()
        self.Screen_Graphs.setObjectName(u"Screen_Graphs")
        self.title_Graphs = QLabel(self.Screen_Graphs)
        self.title_Graphs.setObjectName(u"title_Graphs")
        self.title_Graphs.setGeometry(QRect(60, 40, 491, 71))
        self.title_Graphs.setFont(font1)
        self.title_Graphs.setTextFormat(Qt.AutoText)
        self.title_Graphs.setScaledContents(False)
        self.title_Graphs.setWordWrap(False)
        self.title_Graphs.setIndent(-1)
        self.graph_Test = QChartView(self.Screen_Graphs)
        self.graph_Test.setObjectName(u"graph_Test")
        self.graph_Test.setGeometry(QRect(90, 130, 701, 341))
        self.gridLayoutWidget = QWidget(self.Screen_Graphs)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(798, 210, 239, 141))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.btn_Graph_up = QPushButton(self.gridLayoutWidget)
        self.btn_Graph_up.setObjectName(u"btn_Graph_up")

        self.gridLayout.addWidget(self.btn_Graph_up, 0, 1, 1, 1)

        self.btn_Graph_down = QPushButton(self.gridLayoutWidget)
        self.btn_Graph_down.setObjectName(u"btn_Graph_down")

        self.gridLayout.addWidget(self.btn_Graph_down, 1, 1, 1, 1)

        self.btn_Graph_left = QPushButton(self.gridLayoutWidget)
        self.btn_Graph_left.setObjectName(u"btn_Graph_left")

        self.gridLayout.addWidget(self.btn_Graph_left, 1, 0, 1, 1)

        self.btn_Graph_right = QPushButton(self.gridLayoutWidget)
        self.btn_Graph_right.setObjectName(u"btn_Graph_right")

        self.gridLayout.addWidget(self.btn_Graph_right, 1, 2, 1, 1)

        self.btn_Graph_zout = QPushButton(self.gridLayoutWidget)
        self.btn_Graph_zout.setObjectName(u"btn_Graph_zout")

        self.gridLayout.addWidget(self.btn_Graph_zout, 0, 0, 1, 1)

        self.btn_Graph_zin = QPushButton(self.gridLayoutWidget)
        self.btn_Graph_zin.setObjectName(u"btn_Graph_zin")

        self.gridLayout.addWidget(self.btn_Graph_zin, 0, 2, 1, 1)

        self.btn_Graph_resetview = QPushButton(self.gridLayoutWidget)
        self.btn_Graph_resetview.setObjectName(u"btn_Graph_resetview")

        self.gridLayout.addWidget(self.btn_Graph_resetview, 2, 1, 1, 1)

        self.Screen.addWidget(self.Screen_Graphs)
        self.Screen_Settings = QWidget()
        self.Screen_Settings.setObjectName(u"Screen_Settings")
        self.title_Settings = QLabel(self.Screen_Settings)
        self.title_Settings.setObjectName(u"title_Settings")
        self.title_Settings.setGeometry(QRect(100, 50, 491, 71))
        self.title_Settings.setFont(font1)
        self.title_Settings.setTextFormat(Qt.AutoText)
        self.title_Settings.setScaledContents(False)
        self.title_Settings.setWordWrap(False)
        self.title_Settings.setIndent(-1)
        self.Screen.addWidget(self.Screen_Settings)
        self.Screen_Errors = QWidget()
        self.Screen_Errors.setObjectName(u"Screen_Errors")
        self.Subscreens_Errors = QStackedWidget(self.Screen_Errors)
        self.Subscreens_Errors.setObjectName(u"Subscreens_Errors")
        self.Subscreens_Errors.setGeometry(QRect(0, 0, 1024, 521))
        self.SubScreen_Errors_Basic = QWidget()
        self.SubScreen_Errors_Basic.setObjectName(u"SubScreen_Errors_Basic")
        self.verticalLayoutWidget = QWidget(self.SubScreen_Errors_Basic)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(0, 0, 1021, 521))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.title_Errors_basic = QLabel(self.verticalLayoutWidget)
        self.title_Errors_basic.setObjectName(u"title_Errors_basic")
        self.title_Errors_basic.setFont(font1)
        self.title_Errors_basic.setTextFormat(Qt.AutoText)
        self.title_Errors_basic.setScaledContents(False)
        self.title_Errors_basic.setWordWrap(False)
        self.title_Errors_basic.setIndent(-1)

        self.horizontalLayout_4.addWidget(self.title_Errors_basic)

        self.horizontalSpacer_2 = QSpacerItem(200, 1, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer_2)

        self.btn_Errors_InstanceHistory_basic = QPushButton(self.verticalLayoutWidget)
        self.btn_Errors_InstanceHistory_basic.setObjectName(u"btn_Errors_InstanceHistory_basic")
        sizePolicy2.setHeightForWidth(self.btn_Errors_InstanceHistory_basic.sizePolicy().hasHeightForWidth())
        self.btn_Errors_InstanceHistory_basic.setSizePolicy(sizePolicy2)
        self.btn_Errors_InstanceHistory_basic.setMinimumSize(QSize(300, 60))
        self.btn_Errors_InstanceHistory_basic.setMaximumSize(QSize(150, 60))
        font4 = QFont()
        font4.setPointSize(20)
        self.btn_Errors_InstanceHistory_basic.setFont(font4)
        self.btn_Errors_InstanceHistory_basic.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.btn_Errors_InstanceHistory_basic.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        icon6 = QIcon()
        icon6.addFile(u":/Errors/errors/current history.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Errors_InstanceHistory_basic.setIcon(icon6)
        self.btn_Errors_InstanceHistory_basic.setIconSize(QSize(48, 48))
        self.btn_Errors_InstanceHistory_basic.setCheckable(True)
        self.btn_Errors_InstanceHistory_basic.setChecked(True)
        self.btn_Errors_InstanceHistory_basic.setAutoExclusive(True)
        self.btn_Errors_InstanceHistory_basic.setFlat(True)

        self.horizontalLayout_4.addWidget(self.btn_Errors_InstanceHistory_basic)

        self.btn_Errors_AllHistory_basic = QPushButton(self.verticalLayoutWidget)
        self.btn_Errors_AllHistory_basic.setObjectName(u"btn_Errors_AllHistory_basic")
        sizePolicy2.setHeightForWidth(self.btn_Errors_AllHistory_basic.sizePolicy().hasHeightForWidth())
        self.btn_Errors_AllHistory_basic.setSizePolicy(sizePolicy2)
        self.btn_Errors_AllHistory_basic.setMinimumSize(QSize(300, 60))
        self.btn_Errors_AllHistory_basic.setMaximumSize(QSize(150, 60))
        self.btn_Errors_AllHistory_basic.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_Errors_AllHistory_basic.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        icon7 = QIcon()
        icon7.addFile(u":/Errors/errors/all history.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Errors_AllHistory_basic.setIcon(icon7)
        self.btn_Errors_AllHistory_basic.setIconSize(QSize(48, 48))
        self.btn_Errors_AllHistory_basic.setCheckable(True)
        self.btn_Errors_AllHistory_basic.setAutoExclusive(True)
        self.btn_Errors_AllHistory_basic.setFlat(True)

        self.horizontalLayout_4.addWidget(self.btn_Errors_AllHistory_basic)

        self.horizontalSpacer_3 = QSpacerItem(5, 5, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer_3)

        self.btn_Errors_Refresh_basic = QPushButton(self.verticalLayoutWidget)
        self.btn_Errors_Refresh_basic.setObjectName(u"btn_Errors_Refresh_basic")
        sizePolicy2.setHeightForWidth(self.btn_Errors_Refresh_basic.sizePolicy().hasHeightForWidth())
        self.btn_Errors_Refresh_basic.setSizePolicy(sizePolicy2)
        self.btn_Errors_Refresh_basic.setMinimumSize(QSize(50, 50))
        self.btn_Errors_Refresh_basic.setMaximumSize(QSize(50, 50))
        icon8 = QIcon()
        icon8.addFile(u":/Errors/errors/refresh.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Errors_Refresh_basic.setIcon(icon8)
        self.btn_Errors_Refresh_basic.setIconSize(QSize(48, 40))
        self.btn_Errors_Refresh_basic.setCheckable(True)
        self.btn_Errors_Refresh_basic.setAutoRepeat(True)
        self.btn_Errors_Refresh_basic.setFlat(False)

        self.horizontalLayout_4.addWidget(self.btn_Errors_Refresh_basic)


        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.terminal_basic = QTextEdit(self.verticalLayoutWidget)
        self.terminal_basic.setObjectName(u"terminal_basic")
        self.terminal_basic.viewport().setProperty(u"cursor", QCursor(Qt.CursorShape.SizeVerCursor))
        self.terminal_basic.setTabletTracking(True)
        self.terminal_basic.setAutoFillBackground(False)
        self.terminal_basic.setReadOnly(True)

        self.verticalLayout.addWidget(self.terminal_basic)

        self.Subscreens_Errors.addWidget(self.SubScreen_Errors_Basic)
        self.SubScreen_Errors_Admin = QWidget()
        self.SubScreen_Errors_Admin.setObjectName(u"SubScreen_Errors_Admin")
        sizePolicy2.setHeightForWidth(self.SubScreen_Errors_Admin.sizePolicy().hasHeightForWidth())
        self.SubScreen_Errors_Admin.setSizePolicy(sizePolicy2)
        self.SubScreen_Errors_Admin.setMinimumSize(QSize(1024, 525))
        self.SubScreen_Errors_Admin.setMaximumSize(QSize(1024, 525))
        self.verticalLayoutWidget_2 = QWidget(self.SubScreen_Errors_Admin)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(0, 0, 1021, 521))
        self.verticalLayout_2 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.title_Errors_admin = QLabel(self.verticalLayoutWidget_2)
        self.title_Errors_admin.setObjectName(u"title_Errors_admin")
        self.title_Errors_admin.setFont(font1)
        self.title_Errors_admin.setTextFormat(Qt.AutoText)
        self.title_Errors_admin.setScaledContents(False)
        self.title_Errors_admin.setWordWrap(False)
        self.title_Errors_admin.setIndent(-1)

        self.horizontalLayout_7.addWidget(self.title_Errors_admin)

        self.horizontalSpacer_5 = QSpacerItem(200, 1, QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_7.addItem(self.horizontalSpacer_5)

        self.btn_Errors_InstanceHistory_admin = QPushButton(self.verticalLayoutWidget_2)
        self.btn_Errors_InstanceHistory_admin.setObjectName(u"btn_Errors_InstanceHistory_admin")
        sizePolicy2.setHeightForWidth(self.btn_Errors_InstanceHistory_admin.sizePolicy().hasHeightForWidth())
        self.btn_Errors_InstanceHistory_admin.setSizePolicy(sizePolicy2)
        self.btn_Errors_InstanceHistory_admin.setMinimumSize(QSize(300, 60))
        self.btn_Errors_InstanceHistory_admin.setMaximumSize(QSize(150, 60))
        self.btn_Errors_InstanceHistory_admin.setFont(font4)
        self.btn_Errors_InstanceHistory_admin.setAutoFillBackground(False)
        self.btn_Errors_InstanceHistory_admin.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.btn_Errors_InstanceHistory_admin.setIcon(icon6)
        self.btn_Errors_InstanceHistory_admin.setIconSize(QSize(48, 48))
        self.btn_Errors_InstanceHistory_admin.setCheckable(True)
        self.btn_Errors_InstanceHistory_admin.setChecked(True)
        self.btn_Errors_InstanceHistory_admin.setFlat(True)

        self.horizontalLayout_7.addWidget(self.btn_Errors_InstanceHistory_admin)

        self.btn_Errors_AllHistory_admin = QPushButton(self.verticalLayoutWidget_2)
        self.btn_Errors_AllHistory_admin.setObjectName(u"btn_Errors_AllHistory_admin")
        sizePolicy2.setHeightForWidth(self.btn_Errors_AllHistory_admin.sizePolicy().hasHeightForWidth())
        self.btn_Errors_AllHistory_admin.setSizePolicy(sizePolicy2)
        self.btn_Errors_AllHistory_admin.setMinimumSize(QSize(300, 60))
        self.btn_Errors_AllHistory_admin.setMaximumSize(QSize(150, 60))
        self.btn_Errors_AllHistory_admin.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.btn_Errors_AllHistory_admin.setIcon(icon7)
        self.btn_Errors_AllHistory_admin.setIconSize(QSize(48, 48))
        self.btn_Errors_AllHistory_admin.setCheckable(True)
        self.btn_Errors_AllHistory_admin.setAutoExclusive(True)
        self.btn_Errors_AllHistory_admin.setFlat(True)

        self.horizontalLayout_7.addWidget(self.btn_Errors_AllHistory_admin)

        self.horizontalSpacer_6 = QSpacerItem(5, 1, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_7.addItem(self.horizontalSpacer_6)

        self.btn_Errors_Refresh_admin = QPushButton(self.verticalLayoutWidget_2)
        self.btn_Errors_Refresh_admin.setObjectName(u"btn_Errors_Refresh_admin")
        sizePolicy2.setHeightForWidth(self.btn_Errors_Refresh_admin.sizePolicy().hasHeightForWidth())
        self.btn_Errors_Refresh_admin.setSizePolicy(sizePolicy2)
        self.btn_Errors_Refresh_admin.setMinimumSize(QSize(50, 50))
        self.btn_Errors_Refresh_admin.setMaximumSize(QSize(50, 50))
        self.btn_Errors_Refresh_admin.setStyleSheet(u"")
        self.btn_Errors_Refresh_admin.setIcon(icon8)
        self.btn_Errors_Refresh_admin.setIconSize(QSize(40, 40))
        self.btn_Errors_Refresh_admin.setCheckable(True)
        self.btn_Errors_Refresh_admin.setAutoRepeat(True)
        self.btn_Errors_Refresh_admin.setAutoExclusive(False)
        self.btn_Errors_Refresh_admin.setFlat(True)

        self.horizontalLayout_7.addWidget(self.btn_Errors_Refresh_admin)


        self.verticalLayout_2.addLayout(self.horizontalLayout_7)

        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.terminal_typefield_admin = QLineEdit(self.verticalLayoutWidget_2)
        self.terminal_typefield_admin.setObjectName(u"terminal_typefield_admin")
        self.terminal_typefield_admin.setMinimumSize(QSize(0, 50))
        font5 = QFont()
        font5.setPointSize(16)
        self.terminal_typefield_admin.setFont(font5)
        self.terminal_typefield_admin.setClearButtonEnabled(False)

        self.horizontalLayout_8.addWidget(self.terminal_typefield_admin)

        self.horizontalSpacer = QSpacerItem(5, 1, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_8.addItem(self.horizontalSpacer)

        self.btn_Errors_Send_admin = QPushButton(self.verticalLayoutWidget_2)
        self.btn_Errors_Send_admin.setObjectName(u"btn_Errors_Send_admin")
        sizePolicy2.setHeightForWidth(self.btn_Errors_Send_admin.sizePolicy().hasHeightForWidth())
        self.btn_Errors_Send_admin.setSizePolicy(sizePolicy2)
        self.btn_Errors_Send_admin.setMinimumSize(QSize(50, 50))
        self.btn_Errors_Send_admin.setMaximumSize(QSize(50, 50))
        self.btn_Errors_Send_admin.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_Errors_Send_admin.setAutoFillBackground(True)
        self.btn_Errors_Send_admin.setStyleSheet(u"")
        icon9 = QIcon()
        icon9.addFile(u":/Errors/errors/send.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Errors_Send_admin.setIcon(icon9)
        self.btn_Errors_Send_admin.setIconSize(QSize(40, 40))
        self.btn_Errors_Send_admin.setFlat(True)

        self.horizontalLayout_8.addWidget(self.btn_Errors_Send_admin)


        self.verticalLayout_2.addLayout(self.horizontalLayout_8)

        self.terminal_admin = QTextEdit(self.verticalLayoutWidget_2)
        self.terminal_admin.setObjectName(u"terminal_admin")
        self.terminal_admin.viewport().setProperty(u"cursor", QCursor(Qt.CursorShape.SizeVerCursor))
        self.terminal_admin.setTabletTracking(True)
        self.terminal_admin.setAutoFillBackground(False)
        self.terminal_admin.setReadOnly(True)

        self.verticalLayout_2.addWidget(self.terminal_admin)

        self.Subscreens_Errors.addWidget(self.SubScreen_Errors_Admin)
        self.Screen.addWidget(self.Screen_Errors)

        self.horizontalLayout_2.addWidget(self.Screen)


        self.retranslateUi(Main)

        self.btn_Measure.setDefault(False)
        self.btn_Graphs.setDefault(False)
        self.btn_Settings.setDefault(False)
        self.btn_Errors.setDefault(False)
        self.Screen.setCurrentIndex(1)
        self.Subscreens_Errors.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Main)
    # setupUi

    def retranslateUi(self, Main):
        Main.setWindowTitle(QCoreApplication.translate("Main", u"Form", None))
        self.btn_Measure.setText("")
        self.btn_Graphs.setText("")
        self.btn_Settings.setText("")
        self.btn_Errors.setText("")
        self.logo_Polsl.setText("")
        self.logoMt.setText("")
        self.title_MeasureMain.setText(QCoreApplication.translate("Main", u"Pomiary", None))
        self.btn_StartMeasure.setText(QCoreApplication.translate("Main", u"Wykonaj Pomiar", None))
        self.btn_MeasureToGraph.setText(QCoreApplication.translate("Main", u"Przejd\u017a do poprzedniego Pomiaru", None))
        self.btn_StopMeasure.setText(QCoreApplication.translate("Main", u"Zatrzymaj Proces", None))
        self.title_MeasureProgress.setText(QCoreApplication.translate("Main", u"Wykonywanie Pomiaru", None))
        self.text_MeasureProgress_Step1_1.setText(QCoreApplication.translate("Main", u"Zabezpieczenia zosta\u0142y zdj\u0119te.\n"
"Prosz\u0119 otworzy\u0107 komor\u0119 i\n"
" umie\u015bci\u0107 pr\u00f3bk\u0119 wewn\u0105trz.\n"
"\n"
"Po upewnieniu si\u0119 o poprawnym w\u0142o\u017ceniu pr\u00f3bki,\n"
" prosz\u0119 nacisn\u0105\u0107 przycisk obok by kontynuowa\u0107 proces.", None))
        self.Btn_MeasureProgress_Step1_ObjectReady.setText("")
        self.text_MeasureProgress_Step1_2.setText(QCoreApplication.translate("Main", u"Gotowe", None))
        self.Dsp_MeasureProgress_Step_4.setText("")
        self.Dsp_MeasureProgress_Step_3.setText("")
        self.Dsp_MeasureProgress_Step_2.setText("")
        self.Dsp_MeasureProgress_Step_1.setText("")
        self.title_Graphs.setText(QCoreApplication.translate("Main", u"Wykresy", None))
        self.btn_Graph_up.setText(QCoreApplication.translate("Main", u"G\u00f3ra", None))
        self.btn_Graph_down.setText(QCoreApplication.translate("Main", u"D\u00f3\u0142", None))
        self.btn_Graph_left.setText(QCoreApplication.translate("Main", u"Lewo", None))
        self.btn_Graph_right.setText(QCoreApplication.translate("Main", u"Prawo", None))
        self.btn_Graph_zout.setText(QCoreApplication.translate("Main", u"Zoom out", None))
        self.btn_Graph_zin.setText(QCoreApplication.translate("Main", u"Zoom in", None))
        self.btn_Graph_resetview.setText(QCoreApplication.translate("Main", u"Graph Reset", None))
        self.title_Settings.setText(QCoreApplication.translate("Main", u"Ustawienia", None))
        self.title_Errors_basic.setText(QCoreApplication.translate("Main", u"B\u0142\u0119dy", None))
        self.btn_Errors_InstanceHistory_basic.setText("")
        self.btn_Errors_AllHistory_basic.setText("")
        self.btn_Errors_Refresh_basic.setText("")
        self.terminal_basic.setPlaceholderText("")
        self.title_Errors_admin.setText(QCoreApplication.translate("Main", u"Terminal", None))
        self.btn_Errors_InstanceHistory_admin.setText("")
        self.btn_Errors_AllHistory_admin.setText("")
        self.btn_Errors_Refresh_admin.setText("")
        self.btn_Errors_Send_admin.setText("")
        self.terminal_admin.setPlaceholderText("")
    # retranslateUi

