# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCharts import QChartView
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGridLayout, QHBoxLayout,
    QLabel, QLayout, QLineEdit, QProgressBar,
    QPushButton, QScrollArea, QSizePolicy, QSpacerItem,
    QStackedWidget, QTextEdit, QVBoxLayout, QWidget)
from icons import Icons_rc

class Ui_Main(object):
    def setupUi(self, Main):
        if not Main.objectName():
            Main.setObjectName(u"Main")
        Main.resize(1024, 600)
        Main.setMinimumSize(QSize(1024, 600))
        Main.setMaximumSize(QSize(1024, 600))
        self.Menu = QFrame(Main)
        self.Menu.setObjectName(u"Menu")
        self.Menu.setEnabled(True)
        self.Menu.setGeometry(QRect(0, 0, 1024, 75))
        self.Menu.setMinimumSize(QSize(0, 75))
        self.Menu.setMaximumSize(QSize(16777215, 75))
        self.Menu.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.0113636 rgba(225, 225, 225, 255), stop:1 rgba(245, 245, 245, 255));")
        self.Menu.setFrameShape(QFrame.NoFrame)
        self.Menu.setFrameShadow(QFrame.Raised)
        self.horizontalLayoutWidget = QWidget(self.Menu)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(0, 0, 1031, 81))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(20, 5, 20, 10)
        self.btn_Measure = QPushButton(self.horizontalLayoutWidget)
        self.btn_Measure.setObjectName(u"btn_Measure")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Measure.sizePolicy().hasHeightForWidth())
        self.btn_Measure.setSizePolicy(sizePolicy)
        self.btn_Measure.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_Measure.setAcceptDrops(False)
        self.btn_Measure.setAutoFillBackground(False)
        self.btn_Measure.setStyleSheet(u"border-bottom-color: rgb(255, 85, 0);")
        icon = QIcon()
        icon.addFile(u":/Menu/menu/Measure.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Measure.setIcon(icon)
        self.btn_Measure.setIconSize(QSize(48, 48))
        self.btn_Measure.setCheckable(True)
        self.btn_Measure.setChecked(True)
        self.btn_Measure.setAutoRepeat(False)
        self.btn_Measure.setAutoExclusive(True)
        self.btn_Measure.setAutoDefault(False)
        self.btn_Measure.setFlat(True)

        self.horizontalLayout.addWidget(self.btn_Measure)

        self.btn_Graphs = QPushButton(self.horizontalLayoutWidget)
        self.btn_Graphs.setObjectName(u"btn_Graphs")
        sizePolicy.setHeightForWidth(self.btn_Graphs.sizePolicy().hasHeightForWidth())
        self.btn_Graphs.setSizePolicy(sizePolicy)
        self.btn_Graphs.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_Graphs.setAcceptDrops(False)
        self.btn_Graphs.setAutoFillBackground(False)
        self.btn_Graphs.setStyleSheet(u"border-bottom-color: rgb(255, 85, 0);")
        icon1 = QIcon()
        icon1.addFile(u":/Menu/menu/Graph.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Graphs.setIcon(icon1)
        self.btn_Graphs.setIconSize(QSize(48, 48))
        self.btn_Graphs.setCheckable(True)
        self.btn_Graphs.setChecked(False)
        self.btn_Graphs.setAutoRepeat(False)
        self.btn_Graphs.setAutoExclusive(True)
        self.btn_Graphs.setAutoDefault(False)
        self.btn_Graphs.setFlat(True)

        self.horizontalLayout.addWidget(self.btn_Graphs)

        self.btn_Settings = QPushButton(self.horizontalLayoutWidget)
        self.btn_Settings.setObjectName(u"btn_Settings")
        sizePolicy.setHeightForWidth(self.btn_Settings.sizePolicy().hasHeightForWidth())
        self.btn_Settings.setSizePolicy(sizePolicy)
        self.btn_Settings.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_Settings.setAcceptDrops(False)
        self.btn_Settings.setAutoFillBackground(False)
        self.btn_Settings.setStyleSheet(u"border-bottom-color: rgb(255, 85, 0);")
        icon2 = QIcon()
        icon2.addFile(u":/Menu/menu/Settings.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Settings.setIcon(icon2)
        self.btn_Settings.setIconSize(QSize(48, 48))
        self.btn_Settings.setCheckable(True)
        self.btn_Settings.setChecked(False)
        self.btn_Settings.setAutoRepeat(False)
        self.btn_Settings.setAutoExclusive(True)
        self.btn_Settings.setAutoDefault(False)
        self.btn_Settings.setFlat(True)

        self.horizontalLayout.addWidget(self.btn_Settings)

        self.btn_Errors = QPushButton(self.horizontalLayoutWidget)
        self.btn_Errors.setObjectName(u"btn_Errors")
        sizePolicy.setHeightForWidth(self.btn_Errors.sizePolicy().hasHeightForWidth())
        self.btn_Errors.setSizePolicy(sizePolicy)
        self.btn_Errors.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_Errors.setAcceptDrops(False)
        self.btn_Errors.setAutoFillBackground(False)
        self.btn_Errors.setStyleSheet(u"border-bottom-color: rgb(255, 85, 0);")
        icon3 = QIcon()
        icon3.addFile(u":/Menu/menu/Error.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Errors.setIcon(icon3)
        self.btn_Errors.setIconSize(QSize(48, 48))
        self.btn_Errors.setCheckable(True)
        self.btn_Errors.setChecked(False)
        self.btn_Errors.setAutoRepeat(False)
        self.btn_Errors.setAutoExclusive(True)
        self.btn_Errors.setAutoDefault(False)
        self.btn_Errors.setFlat(True)

        self.horizontalLayout.addWidget(self.btn_Errors)

        self.Content = QFrame(Main)
        self.Content.setObjectName(u"Content")
        self.Content.setGeometry(QRect(0, 75, 1024, 525))
        font = QFont()
        font.setFamilies([u"Futura Std Book"])
        self.Content.setFont(font)
        self.Content.setStyleSheet(u"")
        self.Content.setFrameShape(QFrame.NoFrame)
        self.Content.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.Content)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.Screen = QStackedWidget(self.Content)
        self.Screen.setObjectName(u"Screen")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.Screen.sizePolicy().hasHeightForWidth())
        self.Screen.setSizePolicy(sizePolicy1)
        self.Screen_Logo = QWidget()
        self.Screen_Logo.setObjectName(u"Screen_Logo")
        self.horizontalLayoutWidget_2 = QWidget(self.Screen_Logo)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(0, -69, 1031, 601))
        self.horizontalLayout_3 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(50, 50, 50, 100)
        self.logo_Polsl = QLabel(self.horizontalLayoutWidget_2)
        self.logo_Polsl.setObjectName(u"logo_Polsl")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.logo_Polsl.sizePolicy().hasHeightForWidth())
        self.logo_Polsl.setSizePolicy(sizePolicy2)
        self.logo_Polsl.setMinimumSize(QSize(250, 250))
        self.logo_Polsl.setMaximumSize(QSize(250, 250))
        self.logo_Polsl.setBaseSize(QSize(478, 700))
        self.logo_Polsl.setPixmap(QPixmap(u":/Logo/logo/polsl.png"))
        self.logo_Polsl.setScaledContents(True)
        self.logo_Polsl.setWordWrap(False)

        self.horizontalLayout_3.addWidget(self.logo_Polsl)

        self.logoMt = QLabel(self.horizontalLayoutWidget_2)
        self.logoMt.setObjectName(u"logoMt")
        sizePolicy2.setHeightForWidth(self.logoMt.sizePolicy().hasHeightForWidth())
        self.logoMt.setSizePolicy(sizePolicy2)
        self.logoMt.setMinimumSize(QSize(250, 250))
        self.logoMt.setMaximumSize(QSize(250, 250))
        self.logoMt.setBaseSize(QSize(478, 700))
        self.logoMt.setPixmap(QPixmap(u":/Logo/logo/mt.png"))
        self.logoMt.setScaledContents(True)
        self.logoMt.setWordWrap(False)

        self.horizontalLayout_3.addWidget(self.logoMt)

        self.Screen.addWidget(self.Screen_Logo)
        self.Screen_MeasureMain = QWidget()
        self.Screen_MeasureMain.setObjectName(u"Screen_MeasureMain")
        self.btn_StartMeasure = QPushButton(self.Screen_MeasureMain)
        self.btn_StartMeasure.setObjectName(u"btn_StartMeasure")
        self.btn_StartMeasure.setGeometry(QRect(360, 210, 281, 91))
        font1 = QFont()
        font1.setFamilies([u"Futura Std Book"])
        font1.setPointSize(24)
        self.btn_StartMeasure.setFont(font1)
        self.btn_StartMeasure.setStyleSheet(u"background-color: rgb(191, 191, 191);")
        self.btn_MeasureToGraph = QPushButton(self.Screen_MeasureMain)
        self.btn_MeasureToGraph.setObjectName(u"btn_MeasureToGraph")
        self.btn_MeasureToGraph.setGeometry(QRect(250, 320, 531, 91))
        self.btn_MeasureToGraph.setFont(font1)
        self.btn_MeasureToGraph.setAutoFillBackground(False)
        self.btn_MeasureToGraph.setStyleSheet(u"background-color: rgb(191, 191, 191);")
        self.btn_MeasureToGraph.setAutoRepeat(False)
        self.title_MeasureProgress_4 = QLabel(self.Screen_MeasureMain)
        self.title_MeasureProgress_4.setObjectName(u"title_MeasureProgress_4")
        self.title_MeasureProgress_4.setGeometry(QRect(21, 21, 491, 71))
        font2 = QFont()
        font2.setFamilies([u"Futura Std Book"])
        font2.setPointSize(36)
        self.title_MeasureProgress_4.setFont(font2)
        self.title_MeasureProgress_4.setTextFormat(Qt.AutoText)
        self.title_MeasureProgress_4.setScaledContents(False)
        self.title_MeasureProgress_4.setWordWrap(False)
        self.title_MeasureProgress_4.setIndent(-1)
        self.Screen.addWidget(self.Screen_MeasureMain)
        self.Screen_MeasureProgress = QWidget()
        self.Screen_MeasureProgress.setObjectName(u"Screen_MeasureProgress")
        self.btn_StopMeasure = QPushButton(self.Screen_MeasureProgress)
        self.btn_StopMeasure.setObjectName(u"btn_StopMeasure")
        self.btn_StopMeasure.setGeometry(QRect(730, 90, 261, 61))
        self.btn_StopMeasure.setFont(font1)
        self.btn_StopMeasure.setStyleSheet(u"background-color: rgb(191, 191, 191);")
        self.SubScreens_Measure = QStackedWidget(self.Screen_MeasureProgress)
        self.SubScreens_Measure.setObjectName(u"SubScreens_Measure")
        self.SubScreens_Measure.setGeometry(QRect(3, 0, 1021, 521))
        self.SubScreen_Measure_Step1 = QWidget()
        self.SubScreen_Measure_Step1.setObjectName(u"SubScreen_Measure_Step1")
        self.title_MeasureProgress_Step1 = QLabel(self.SubScreen_Measure_Step1)
        self.title_MeasureProgress_Step1.setObjectName(u"title_MeasureProgress_Step1")
        self.title_MeasureProgress_Step1.setGeometry(QRect(120, 50, 491, 71))
        self.title_MeasureProgress_Step1.setFont(font2)
        self.title_MeasureProgress_Step1.setTextFormat(Qt.AutoText)
        self.title_MeasureProgress_Step1.setScaledContents(False)
        self.title_MeasureProgress_Step1.setWordWrap(False)
        self.title_MeasureProgress_Step1.setIndent(-1)
        self.text_MeasureProgress_Step1_1 = QLabel(self.SubScreen_Measure_Step1)
        self.text_MeasureProgress_Step1_1.setObjectName(u"text_MeasureProgress_Step1_1")
        self.text_MeasureProgress_Step1_1.setGeometry(QRect(40, 170, 661, 271))
        font3 = QFont()
        font3.setFamilies([u"Futura Std Book"])
        font3.setPointSize(20)
        self.text_MeasureProgress_Step1_1.setFont(font3)
        self.text_MeasureProgress_Step1_1.setFrameShape(QFrame.Box)
        self.text_MeasureProgress_Step1_1.setFrameShadow(QFrame.Sunken)
        self.text_MeasureProgress_Step1_1.setTextFormat(Qt.AutoText)
        self.text_MeasureProgress_Step1_1.setScaledContents(False)
        self.text_MeasureProgress_Step1_1.setAlignment(Qt.AlignCenter)
        self.text_MeasureProgress_Step1_1.setWordWrap(False)
        self.text_MeasureProgress_Step1_1.setIndent(-1)
        self.btn_Measure_Step1_ObjectReady = QPushButton(self.SubScreen_Measure_Step1)
        self.btn_Measure_Step1_ObjectReady.setObjectName(u"btn_Measure_Step1_ObjectReady")
        self.btn_Measure_Step1_ObjectReady.setGeometry(QRect(760, 240, 200, 200))
        self.btn_Measure_Step1_ObjectReady.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_Measure_Step1_ObjectReady.setLayoutDirection(Qt.LeftToRight)
        icon4 = QIcon()
        icon4.addFile(u":/Progress/progress/Checkmark.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Measure_Step1_ObjectReady.setIcon(icon4)
        self.btn_Measure_Step1_ObjectReady.setIconSize(QSize(128, 128))
        self.btn_Measure_Step1_ObjectReady.setFlat(False)
        self.text_MeasureProgress_Step1_2 = QLabel(self.SubScreen_Measure_Step1)
        self.text_MeasureProgress_Step1_2.setObjectName(u"text_MeasureProgress_Step1_2")
        self.text_MeasureProgress_Step1_2.setGeometry(QRect(816, 380, 91, 71))
        self.text_MeasureProgress_Step1_2.setFont(font3)
        self.text_MeasureProgress_Step1_2.setTextFormat(Qt.AutoText)
        self.text_MeasureProgress_Step1_2.setScaledContents(False)
        self.text_MeasureProgress_Step1_2.setWordWrap(False)
        self.text_MeasureProgress_Step1_2.setIndent(-1)
        self.SubScreens_Measure.addWidget(self.SubScreen_Measure_Step1)
        self.SubScreen_Measure_Step1_Error = QWidget()
        self.SubScreen_Measure_Step1_Error.setObjectName(u"SubScreen_Measure_Step1_Error")
        self.btn_Measure_Step1_Error_Errors = QPushButton(self.SubScreen_Measure_Step1_Error)
        self.btn_Measure_Step1_Error_Errors.setObjectName(u"btn_Measure_Step1_Error_Errors")
        self.btn_Measure_Step1_Error_Errors.setGeometry(QRect(770, 240, 181, 181))
        self.btn_Measure_Step1_Error_Errors.setIcon(icon3)
        self.btn_Measure_Step1_Error_Errors.setIconSize(QSize(128, 128))
        self.btn_Measure_Step1_Error_RefreshCOM = QPushButton(self.SubScreen_Measure_Step1_Error)
        self.btn_Measure_Step1_Error_RefreshCOM.setObjectName(u"btn_Measure_Step1_Error_RefreshCOM")
        self.btn_Measure_Step1_Error_RefreshCOM.setGeometry(QRect(540, 240, 181, 181))
        icon5 = QIcon()
        icon5.addFile(u":/Errors/errors/refresh.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Measure_Step1_Error_RefreshCOM.setIcon(icon5)
        self.btn_Measure_Step1_Error_RefreshCOM.setIconSize(QSize(128, 128))
        self.title_MeasureProgress_Step1_Error = QLabel(self.SubScreen_Measure_Step1_Error)
        self.title_MeasureProgress_Step1_Error.setObjectName(u"title_MeasureProgress_Step1_Error")
        self.title_MeasureProgress_Step1_Error.setGeometry(QRect(120, 50, 491, 71))
        self.title_MeasureProgress_Step1_Error.setFont(font2)
        self.title_MeasureProgress_Step1_Error.setTextFormat(Qt.AutoText)
        self.title_MeasureProgress_Step1_Error.setScaledContents(False)
        self.title_MeasureProgress_Step1_Error.setAlignment(Qt.AlignCenter)
        self.title_MeasureProgress_Step1_Error.setWordWrap(False)
        self.title_MeasureProgress_Step1_Error.setIndent(-1)
        self.dsp_MeasureProgress_Step_1_1 = QPushButton(self.SubScreen_Measure_Step1_Error)
        self.dsp_MeasureProgress_Step_1_1.setObjectName(u"dsp_MeasureProgress_Step_1_1")
        self.dsp_MeasureProgress_Step_1_1.setEnabled(False)
        self.dsp_MeasureProgress_Step_1_1.setGeometry(QRect(90, 260, 60, 56))
        icon6 = QIcon()
        icon6.addFile(u":/Progress/progress/Empty.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon6.addFile(u":/Progress/progress/True.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        icon6.addFile(u":/Progress/progress/Empty.png", QSize(), QIcon.Mode.Disabled, QIcon.State.Off)
        icon6.addFile(u":/Progress/progress/True.png", QSize(), QIcon.Mode.Disabled, QIcon.State.On)
        self.dsp_MeasureProgress_Step_1_1.setIcon(icon6)
        self.dsp_MeasureProgress_Step_1_1.setIconSize(QSize(48, 48))
        self.dsp_MeasureProgress_Step_1_1.setFlat(True)
        self.dsp_MeasureProgress_Step_1_2 = QPushButton(self.SubScreen_Measure_Step1_Error)
        self.dsp_MeasureProgress_Step_1_2.setObjectName(u"dsp_MeasureProgress_Step_1_2")
        self.dsp_MeasureProgress_Step_1_2.setEnabled(False)
        self.dsp_MeasureProgress_Step_1_2.setGeometry(QRect(90, 350, 60, 56))
        self.dsp_MeasureProgress_Step_1_2.setIcon(icon6)
        self.dsp_MeasureProgress_Step_1_2.setIconSize(QSize(48, 48))
        self.dsp_MeasureProgress_Step_1_2.setFlat(True)
        self.text_MeasureProgress_Step1_Error_2 = QLabel(self.SubScreen_Measure_Step1_Error)
        self.text_MeasureProgress_Step1_Error_2.setObjectName(u"text_MeasureProgress_Step1_Error_2")
        self.text_MeasureProgress_Step1_Error_2.setGeometry(QRect(190, 260, 311, 51))
        self.text_MeasureProgress_Step1_Error_2.setFont(font3)
        self.text_MeasureProgress_Step1_Error_2.setFrameShape(QFrame.Box)
        self.text_MeasureProgress_Step1_Error_2.setFrameShadow(QFrame.Sunken)
        self.text_MeasureProgress_Step1_Error_2.setTextFormat(Qt.AutoText)
        self.text_MeasureProgress_Step1_Error_2.setScaledContents(False)
        self.text_MeasureProgress_Step1_Error_2.setAlignment(Qt.AlignCenter)
        self.text_MeasureProgress_Step1_Error_2.setWordWrap(False)
        self.text_MeasureProgress_Step1_Error_2.setIndent(-1)
        self.text_MeasureProgress_Step1_Error_3 = QLabel(self.SubScreen_Measure_Step1_Error)
        self.text_MeasureProgress_Step1_Error_3.setObjectName(u"text_MeasureProgress_Step1_Error_3")
        self.text_MeasureProgress_Step1_Error_3.setGeometry(QRect(190, 350, 311, 51))
        self.text_MeasureProgress_Step1_Error_3.setFont(font3)
        self.text_MeasureProgress_Step1_Error_3.setFrameShape(QFrame.Box)
        self.text_MeasureProgress_Step1_Error_3.setFrameShadow(QFrame.Sunken)
        self.text_MeasureProgress_Step1_Error_3.setTextFormat(Qt.AutoText)
        self.text_MeasureProgress_Step1_Error_3.setScaledContents(False)
        self.text_MeasureProgress_Step1_Error_3.setAlignment(Qt.AlignCenter)
        self.text_MeasureProgress_Step1_Error_3.setWordWrap(False)
        self.text_MeasureProgress_Step1_Error_3.setIndent(-1)
        self.text_MeasureProgress_Step1_Error_1 = QLabel(self.SubScreen_Measure_Step1_Error)
        self.text_MeasureProgress_Step1_Error_1.setObjectName(u"text_MeasureProgress_Step1_Error_1")
        self.text_MeasureProgress_Step1_Error_1.setGeometry(QRect(120, 130, 491, 91))
        self.text_MeasureProgress_Step1_Error_1.setFont(font3)
        self.text_MeasureProgress_Step1_Error_1.setFrameShape(QFrame.Box)
        self.text_MeasureProgress_Step1_Error_1.setFrameShadow(QFrame.Sunken)
        self.text_MeasureProgress_Step1_Error_1.setTextFormat(Qt.AutoText)
        self.text_MeasureProgress_Step1_Error_1.setScaledContents(False)
        self.text_MeasureProgress_Step1_Error_1.setAlignment(Qt.AlignCenter)
        self.text_MeasureProgress_Step1_Error_1.setWordWrap(False)
        self.text_MeasureProgress_Step1_Error_1.setIndent(-1)
        self.SubScreens_Measure.addWidget(self.SubScreen_Measure_Step1_Error)
        self.SubScreen_Measure_Step2 = QWidget()
        self.SubScreen_Measure_Step2.setObjectName(u"SubScreen_Measure_Step2")
        self.btn_Measure_Step2_LockSafety = QPushButton(self.SubScreen_Measure_Step2)
        self.btn_Measure_Step2_LockSafety.setObjectName(u"btn_Measure_Step2_LockSafety")
        self.btn_Measure_Step2_LockSafety.setGeometry(QRect(770, 240, 181, 181))
        icon7 = QIcon()
        icon7.addFile(u":/Progress/progress/Unlocked.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon7.addFile(u":/Progress/progress/Locked.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        icon7.addFile(u":/Progress/progress/Unlocked.png", QSize(), QIcon.Mode.Disabled, QIcon.State.Off)
        icon7.addFile(u":/Progress/progress/Locked.png", QSize(), QIcon.Mode.Disabled, QIcon.State.On)
        self.btn_Measure_Step2_LockSafety.setIcon(icon7)
        self.btn_Measure_Step2_LockSafety.setIconSize(QSize(128, 128))
        self.dsp_Measure_Step2_TensionProgressBar = QProgressBar(self.SubScreen_Measure_Step2)
        self.dsp_Measure_Step2_TensionProgressBar.setObjectName(u"dsp_Measure_Step2_TensionProgressBar")
        self.dsp_Measure_Step2_TensionProgressBar.setGeometry(QRect(60, 330, 571, 51))
        self.dsp_Measure_Step2_TensionProgressBar.setValue(24)
        self.dsp_Measure_Step2_TensionProgressBar.setTextDirection(QProgressBar.TopToBottom)
        self.dsp_MeasureProgress_Step_2_1 = QPushButton(self.SubScreen_Measure_Step2)
        self.dsp_MeasureProgress_Step_2_1.setObjectName(u"dsp_MeasureProgress_Step_2_1")
        self.dsp_MeasureProgress_Step_2_1.setEnabled(False)
        self.dsp_MeasureProgress_Step_2_1.setGeometry(QRect(650, 330, 60, 56))
        self.dsp_MeasureProgress_Step_2_1.setIcon(icon6)
        self.dsp_MeasureProgress_Step_2_1.setIconSize(QSize(48, 48))
        self.dsp_MeasureProgress_Step_2_1.setFlat(True)
        self.title_MeasureProgress_Step2 = QLabel(self.SubScreen_Measure_Step2)
        self.title_MeasureProgress_Step2.setObjectName(u"title_MeasureProgress_Step2")
        self.title_MeasureProgress_Step2.setGeometry(QRect(100, 50, 571, 71))
        self.title_MeasureProgress_Step2.setFont(font2)
        self.title_MeasureProgress_Step2.setTextFormat(Qt.AutoText)
        self.title_MeasureProgress_Step2.setScaledContents(False)
        self.title_MeasureProgress_Step2.setWordWrap(False)
        self.title_MeasureProgress_Step2.setIndent(-1)
        self.text_MeasureProgress_Step1_5 = QLabel(self.SubScreen_Measure_Step2)
        self.text_MeasureProgress_Step1_5.setObjectName(u"text_MeasureProgress_Step1_5")
        self.text_MeasureProgress_Step1_5.setGeometry(QRect(100, 140, 571, 141))
        self.text_MeasureProgress_Step1_5.setFont(font3)
        self.text_MeasureProgress_Step1_5.setFrameShape(QFrame.Box)
        self.text_MeasureProgress_Step1_5.setFrameShadow(QFrame.Sunken)
        self.text_MeasureProgress_Step1_5.setTextFormat(Qt.AutoText)
        self.text_MeasureProgress_Step1_5.setScaledContents(False)
        self.text_MeasureProgress_Step1_5.setAlignment(Qt.AlignCenter)
        self.text_MeasureProgress_Step1_5.setWordWrap(False)
        self.text_MeasureProgress_Step1_5.setIndent(-1)
        self.SubScreens_Measure.addWidget(self.SubScreen_Measure_Step2)
        self.SubScreen_Measure_Step2_Error = QWidget()
        self.SubScreen_Measure_Step2_Error.setObjectName(u"SubScreen_Measure_Step2_Error")
        self.title_MeasureProgress_Step2_Error = QLabel(self.SubScreen_Measure_Step2_Error)
        self.title_MeasureProgress_Step2_Error.setObjectName(u"title_MeasureProgress_Step2_Error")
        self.title_MeasureProgress_Step2_Error.setGeometry(QRect(100, 50, 571, 71))
        self.title_MeasureProgress_Step2_Error.setFont(font2)
        self.title_MeasureProgress_Step2_Error.setLayoutDirection(Qt.LeftToRight)
        self.title_MeasureProgress_Step2_Error.setTextFormat(Qt.AutoText)
        self.title_MeasureProgress_Step2_Error.setScaledContents(False)
        self.title_MeasureProgress_Step2_Error.setAlignment(Qt.AlignCenter)
        self.title_MeasureProgress_Step2_Error.setWordWrap(False)
        self.title_MeasureProgress_Step2_Error.setIndent(-1)
        self.btn_Measure_Step2_Error_LockSafety = QPushButton(self.SubScreen_Measure_Step2_Error)
        self.btn_Measure_Step2_Error_LockSafety.setObjectName(u"btn_Measure_Step2_Error_LockSafety")
        self.btn_Measure_Step2_Error_LockSafety.setGeometry(QRect(290, 330, 181, 181))
        icon8 = QIcon()
        icon8.addFile(u":/Progress/progress/Unlocked.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Measure_Step2_Error_LockSafety.setIcon(icon8)
        self.btn_Measure_Step2_Error_LockSafety.setIconSize(QSize(128, 128))
        self.btn_Measure_Step2_Error_Retry = QPushButton(self.SubScreen_Measure_Step2_Error)
        self.btn_Measure_Step2_Error_Retry.setObjectName(u"btn_Measure_Step2_Error_Retry")
        self.btn_Measure_Step2_Error_Retry.setGeometry(QRect(770, 240, 181, 181))
        icon9 = QIcon()
        icon9.addFile(u":/Errors/errors/refresh.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon9.addFile(u":/Progress/progress/Locked.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        icon9.addFile(u":/Progress/progress/Unlocked.png", QSize(), QIcon.Mode.Disabled, QIcon.State.Off)
        icon9.addFile(u":/Progress/progress/Locked.png", QSize(), QIcon.Mode.Disabled, QIcon.State.On)
        self.btn_Measure_Step2_Error_Retry.setIcon(icon9)
        self.btn_Measure_Step2_Error_Retry.setIconSize(QSize(128, 128))
        self.text_MeasureProgress_Step2_Error_1 = QLabel(self.SubScreen_Measure_Step2_Error)
        self.text_MeasureProgress_Step2_Error_1.setObjectName(u"text_MeasureProgress_Step2_Error_1")
        self.text_MeasureProgress_Step2_Error_1.setGeometry(QRect(70, 130, 621, 181))
        self.text_MeasureProgress_Step2_Error_1.setFont(font3)
        self.text_MeasureProgress_Step2_Error_1.setFrameShape(QFrame.Box)
        self.text_MeasureProgress_Step2_Error_1.setFrameShadow(QFrame.Sunken)
        self.text_MeasureProgress_Step2_Error_1.setTextFormat(Qt.AutoText)
        self.text_MeasureProgress_Step2_Error_1.setScaledContents(False)
        self.text_MeasureProgress_Step2_Error_1.setAlignment(Qt.AlignCenter)
        self.text_MeasureProgress_Step2_Error_1.setWordWrap(False)
        self.text_MeasureProgress_Step2_Error_1.setIndent(-1)
        self.dsp_MeasureProgress_Step_2_Error_1 = QPushButton(self.SubScreen_Measure_Step2_Error)
        self.dsp_MeasureProgress_Step_2_Error_1.setObjectName(u"dsp_MeasureProgress_Step_2_Error_1")
        self.dsp_MeasureProgress_Step_2_Error_1.setEnabled(False)
        self.dsp_MeasureProgress_Step_2_Error_1.setGeometry(QRect(490, 390, 61, 61))
        self.dsp_MeasureProgress_Step_2_Error_1.setIcon(icon6)
        self.dsp_MeasureProgress_Step_2_Error_1.setIconSize(QSize(48, 48))
        self.dsp_MeasureProgress_Step_2_Error_1.setFlat(True)
        self.SubScreens_Measure.addWidget(self.SubScreen_Measure_Step2_Error)
        self.SubScreen_Measure_Step2_Reset = QWidget()
        self.SubScreen_Measure_Step2_Reset.setObjectName(u"SubScreen_Measure_Step2_Reset")
        self.title_MeasureProgress_Step2_Reset = QLabel(self.SubScreen_Measure_Step2_Reset)
        self.title_MeasureProgress_Step2_Reset.setObjectName(u"title_MeasureProgress_Step2_Reset")
        self.title_MeasureProgress_Step2_Reset.setGeometry(QRect(100, 50, 571, 71))
        self.title_MeasureProgress_Step2_Reset.setFont(font2)
        self.title_MeasureProgress_Step2_Reset.setLayoutDirection(Qt.LeftToRight)
        self.title_MeasureProgress_Step2_Reset.setTextFormat(Qt.AutoText)
        self.title_MeasureProgress_Step2_Reset.setScaledContents(False)
        self.title_MeasureProgress_Step2_Reset.setAlignment(Qt.AlignCenter)
        self.title_MeasureProgress_Step2_Reset.setWordWrap(False)
        self.title_MeasureProgress_Step2_Reset.setIndent(-1)
        self.text_MeasureProgress_Step2_Error_2 = QLabel(self.SubScreen_Measure_Step2_Reset)
        self.text_MeasureProgress_Step2_Error_2.setObjectName(u"text_MeasureProgress_Step2_Error_2")
        self.text_MeasureProgress_Step2_Error_2.setGeometry(QRect(180, 130, 421, 131))
        self.text_MeasureProgress_Step2_Error_2.setFont(font3)
        self.text_MeasureProgress_Step2_Error_2.setFrameShape(QFrame.Box)
        self.text_MeasureProgress_Step2_Error_2.setFrameShadow(QFrame.Sunken)
        self.text_MeasureProgress_Step2_Error_2.setTextFormat(Qt.AutoText)
        self.text_MeasureProgress_Step2_Error_2.setScaledContents(False)
        self.text_MeasureProgress_Step2_Error_2.setAlignment(Qt.AlignCenter)
        self.text_MeasureProgress_Step2_Error_2.setWordWrap(False)
        self.text_MeasureProgress_Step2_Error_2.setIndent(-1)
        self.btn_Measure_Step2_LockSafety_2 = QPushButton(self.SubScreen_Measure_Step2_Reset)
        self.btn_Measure_Step2_LockSafety_2.setObjectName(u"btn_Measure_Step2_LockSafety_2")
        self.btn_Measure_Step2_LockSafety_2.setGeometry(QRect(300, 290, 181, 181))
        self.btn_Measure_Step2_LockSafety_2.setIcon(icon7)
        self.btn_Measure_Step2_LockSafety_2.setIconSize(QSize(128, 128))
        self.SubScreens_Measure.addWidget(self.SubScreen_Measure_Step2_Reset)
        self.SubScreen_Measure_Step3 = QWidget()
        self.SubScreen_Measure_Step3.setObjectName(u"SubScreen_Measure_Step3")
        self.title_MeasureProgress_Step2_Reset_2 = QLabel(self.SubScreen_Measure_Step3)
        self.title_MeasureProgress_Step2_Reset_2.setObjectName(u"title_MeasureProgress_Step2_Reset_2")
        self.title_MeasureProgress_Step2_Reset_2.setGeometry(QRect(100, 50, 571, 71))
        self.title_MeasureProgress_Step2_Reset_2.setFont(font2)
        self.title_MeasureProgress_Step2_Reset_2.setLayoutDirection(Qt.LeftToRight)
        self.title_MeasureProgress_Step2_Reset_2.setTextFormat(Qt.AutoText)
        self.title_MeasureProgress_Step2_Reset_2.setScaledContents(False)
        self.title_MeasureProgress_Step2_Reset_2.setAlignment(Qt.AlignCenter)
        self.title_MeasureProgress_Step2_Reset_2.setWordWrap(False)
        self.title_MeasureProgress_Step2_Reset_2.setIndent(-1)
        self.graph_Measure_Step3 = QChartView(self.SubScreen_Measure_Step3)
        self.graph_Measure_Step3.setObjectName(u"graph_Measure_Step3")
        self.graph_Measure_Step3.setGeometry(QRect(70, 140, 631, 341))
        self.btn_Measure_Step3 = QPushButton(self.SubScreen_Measure_Step3)
        self.btn_Measure_Step3.setObjectName(u"btn_Measure_Step3")
        self.btn_Measure_Step3.setEnabled(False)
        self.btn_Measure_Step3.setGeometry(QRect(760, 220, 200, 200))
        self.btn_Measure_Step3.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_Measure_Step3.setLayoutDirection(Qt.LeftToRight)
        self.btn_Measure_Step3.setIcon(icon4)
        self.btn_Measure_Step3.setIconSize(QSize(128, 128))
        self.btn_Measure_Step3.setFlat(False)
        self.SubScreens_Measure.addWidget(self.SubScreen_Measure_Step3)
        self.SubScreen_Measure_Step4 = QWidget()
        self.SubScreen_Measure_Step4.setObjectName(u"SubScreen_Measure_Step4")
        self.title_MeasureProgress_Step2_Reset_3 = QLabel(self.SubScreen_Measure_Step4)
        self.title_MeasureProgress_Step2_Reset_3.setObjectName(u"title_MeasureProgress_Step2_Reset_3")
        self.title_MeasureProgress_Step2_Reset_3.setGeometry(QRect(90, 50, 571, 71))
        self.title_MeasureProgress_Step2_Reset_3.setFont(font2)
        self.title_MeasureProgress_Step2_Reset_3.setLayoutDirection(Qt.LeftToRight)
        self.title_MeasureProgress_Step2_Reset_3.setTextFormat(Qt.AutoText)
        self.title_MeasureProgress_Step2_Reset_3.setScaledContents(False)
        self.title_MeasureProgress_Step2_Reset_3.setAlignment(Qt.AlignCenter)
        self.title_MeasureProgress_Step2_Reset_3.setWordWrap(False)
        self.title_MeasureProgress_Step2_Reset_3.setIndent(-1)
        self.SubScreens_Measure.addWidget(self.SubScreen_Measure_Step4)
        self.verticalLayoutWidget_3 = QWidget(self.Screen_MeasureProgress)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(730, 20, 260, 58))
        self.LightIndicatorContainer = QHBoxLayout(self.verticalLayoutWidget_3)
        self.LightIndicatorContainer.setObjectName(u"LightIndicatorContainer")
        self.LightIndicatorContainer.setContentsMargins(0, 0, 0, 0)
        self.dsp_MeasureProgress_Step_1 = QPushButton(self.verticalLayoutWidget_3)
        self.dsp_MeasureProgress_Step_1.setObjectName(u"dsp_MeasureProgress_Step_1")
        self.dsp_MeasureProgress_Step_1.setEnabled(False)
        self.dsp_MeasureProgress_Step_1.setIcon(icon6)
        self.dsp_MeasureProgress_Step_1.setIconSize(QSize(48, 48))
        self.dsp_MeasureProgress_Step_1.setFlat(True)

        self.LightIndicatorContainer.addWidget(self.dsp_MeasureProgress_Step_1)

        self.dsp_MeasureProgress_Step_2 = QPushButton(self.verticalLayoutWidget_3)
        self.dsp_MeasureProgress_Step_2.setObjectName(u"dsp_MeasureProgress_Step_2")
        self.dsp_MeasureProgress_Step_2.setEnabled(False)
        self.dsp_MeasureProgress_Step_2.setIcon(icon6)
        self.dsp_MeasureProgress_Step_2.setIconSize(QSize(48, 48))
        self.dsp_MeasureProgress_Step_2.setFlat(True)

        self.LightIndicatorContainer.addWidget(self.dsp_MeasureProgress_Step_2)

        self.dsp_MeasureProgress_Step_3 = QPushButton(self.verticalLayoutWidget_3)
        self.dsp_MeasureProgress_Step_3.setObjectName(u"dsp_MeasureProgress_Step_3")
        self.dsp_MeasureProgress_Step_3.setEnabled(False)
        self.dsp_MeasureProgress_Step_3.setIcon(icon6)
        self.dsp_MeasureProgress_Step_3.setIconSize(QSize(48, 48))
        self.dsp_MeasureProgress_Step_3.setFlat(True)

        self.LightIndicatorContainer.addWidget(self.dsp_MeasureProgress_Step_3)

        self.dsp_MeasureProgress_Step_4 = QPushButton(self.verticalLayoutWidget_3)
        self.dsp_MeasureProgress_Step_4.setObjectName(u"dsp_MeasureProgress_Step_4")
        self.dsp_MeasureProgress_Step_4.setEnabled(False)
        self.dsp_MeasureProgress_Step_4.setIcon(icon6)
        self.dsp_MeasureProgress_Step_4.setIconSize(QSize(48, 48))
        self.dsp_MeasureProgress_Step_4.setFlat(True)

        self.LightIndicatorContainer.addWidget(self.dsp_MeasureProgress_Step_4)

        self.Screen.addWidget(self.Screen_MeasureProgress)
        self.SubScreens_Measure.raise_()
        self.btn_StopMeasure.raise_()
        self.verticalLayoutWidget_3.raise_()
        self.Screen_Graphs = QWidget()
        self.Screen_Graphs.setObjectName(u"Screen_Graphs")
        self.title_Graphs = QLabel(self.Screen_Graphs)
        self.title_Graphs.setObjectName(u"title_Graphs")
        self.title_Graphs.setGeometry(QRect(21, 21, 491, 60))
        self.title_Graphs.setFont(font2)
        self.title_Graphs.setTextFormat(Qt.AutoText)
        self.title_Graphs.setScaledContents(False)
        self.title_Graphs.setWordWrap(False)
        self.title_Graphs.setIndent(-1)
        self.dsp_graph = QChartView(self.Screen_Graphs)
        self.dsp_graph.setObjectName(u"dsp_graph")
        self.dsp_graph.setGeometry(QRect(30, 160, 711, 351))
        self.gridLayoutWidget = QWidget(self.Screen_Graphs)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(540, 30, 201, 121))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.btn_Graph_right = QPushButton(self.gridLayoutWidget)
        self.btn_Graph_right.setObjectName(u"btn_Graph_right")
        icon10 = QIcon()
        icon10.addFile(u"icons/graph/graph_right.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Graph_right.setIcon(icon10)
        self.btn_Graph_right.setIconSize(QSize(48, 48))

        self.gridLayout.addWidget(self.btn_Graph_right, 1, 2, 1, 1)

        self.btn_Graph_zout = QPushButton(self.gridLayoutWidget)
        self.btn_Graph_zout.setObjectName(u"btn_Graph_zout")
        icon11 = QIcon()
        icon11.addFile(u"icons/graph/graph_zoomout.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Graph_zout.setIcon(icon11)
        self.btn_Graph_zout.setIconSize(QSize(48, 48))

        self.gridLayout.addWidget(self.btn_Graph_zout, 0, 0, 1, 1)

        self.btn_Graph_up = QPushButton(self.gridLayoutWidget)
        self.btn_Graph_up.setObjectName(u"btn_Graph_up")
        icon12 = QIcon()
        icon12.addFile(u"icons/graph/graph_up.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Graph_up.setIcon(icon12)
        self.btn_Graph_up.setIconSize(QSize(48, 48))

        self.gridLayout.addWidget(self.btn_Graph_up, 0, 1, 1, 1)

        self.btn_Graph_left = QPushButton(self.gridLayoutWidget)
        self.btn_Graph_left.setObjectName(u"btn_Graph_left")
        icon13 = QIcon()
        icon13.addFile(u"icons/graph/graph_left.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Graph_left.setIcon(icon13)
        self.btn_Graph_left.setIconSize(QSize(48, 48))

        self.gridLayout.addWidget(self.btn_Graph_left, 1, 0, 1, 1)

        self.btn_Graph_down = QPushButton(self.gridLayoutWidget)
        self.btn_Graph_down.setObjectName(u"btn_Graph_down")
        icon14 = QIcon()
        icon14.addFile(u"icons/graph/graph_down.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Graph_down.setIcon(icon14)
        self.btn_Graph_down.setIconSize(QSize(48, 48))

        self.gridLayout.addWidget(self.btn_Graph_down, 1, 1, 1, 1)

        self.btn_Graph_zin = QPushButton(self.gridLayoutWidget)
        self.btn_Graph_zin.setObjectName(u"btn_Graph_zin")
        icon15 = QIcon()
        icon15.addFile(u"icons/graph/graph_zoomin.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Graph_zin.setIcon(icon15)
        self.btn_Graph_zin.setIconSize(QSize(48, 48))

        self.gridLayout.addWidget(self.btn_Graph_zin, 0, 2, 1, 1)

        self.btn_SaveGraph = QPushButton(self.Screen_Graphs)
        self.btn_SaveGraph.setObjectName(u"btn_SaveGraph")
        self.btn_SaveGraph.setGeometry(QRect(770, 30, 101, 61))
        self.btn_SaveGraph.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon16 = QIcon()
        icon16.addFile(u"icons/graph/Save.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_SaveGraph.setIcon(icon16)
        self.btn_SaveGraph.setIconSize(QSize(48, 48))
        self.btn_LoadGraph = QPushButton(self.Screen_Graphs)
        self.btn_LoadGraph.setObjectName(u"btn_LoadGraph")
        self.btn_LoadGraph.setGeometry(QRect(890, 30, 101, 61))
        self.btn_LoadGraph.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon17 = QIcon()
        icon17.addFile(u"icons/graph/Load.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_LoadGraph.setIcon(icon17)
        self.btn_LoadGraph.setIconSize(QSize(48, 48))
        self.btn_Graph_resetview = QPushButton(self.Screen_Graphs)
        self.btn_Graph_resetview.setObjectName(u"btn_Graph_resetview")
        self.btn_Graph_resetview.setGeometry(QRect(470, 90, 60, 56))
        icon18 = QIcon()
        icon18.addFile(u"icons/graph/refresh_graph.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Graph_resetview.setIcon(icon18)
        self.btn_Graph_resetview.setIconSize(QSize(48, 48))
        self.graph_graphs_list = QScrollArea(self.Screen_Graphs)
        self.graph_graphs_list.setObjectName(u"graph_graphs_list")
        self.graph_graphs_list.setGeometry(QRect(760, 110, 251, 401))
        self.graph_graphs_list.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 249, 399))
        self.graph_graphs_list.setWidget(self.scrollAreaWidgetContents)
        self.Screen.addWidget(self.Screen_Graphs)
        self.Screen_Settings = QWidget()
        self.Screen_Settings.setObjectName(u"Screen_Settings")
        self.verticalLayoutWidget_4 = QWidget(self.Screen_Settings)
        self.verticalLayoutWidget_4.setObjectName(u"verticalLayoutWidget_4")
        self.verticalLayoutWidget_4.setGeometry(QRect(0, 0, 551, 371))
        self.verticalLayout_3 = QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(20, 20, 20, 20)
        self.title_Settings = QLabel(self.verticalLayoutWidget_4)
        self.title_Settings.setObjectName(u"title_Settings")
        self.title_Settings.setFont(font2)
        self.title_Settings.setTextFormat(Qt.AutoText)
        self.title_Settings.setScaledContents(False)
        self.title_Settings.setWordWrap(False)
        self.title_Settings.setIndent(-1)

        self.verticalLayout_3.addWidget(self.title_Settings)

        self.gridLayout_4 = QGridLayout()
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.devMode = QPushButton(self.verticalLayoutWidget_4)
        self.devMode.setObjectName(u"devMode")
        font4 = QFont()
        font4.setFamilies([u"Futura Std Book"])
        font4.setPointSize(16)
        self.devMode.setFont(font4)
        self.devMode.setCheckable(True)
        self.devMode.setAutoExclusive(True)
        self.devMode.setFlat(False)

        self.gridLayout_4.addWidget(self.devMode, 3, 0, 1, 1)

        self.graphSavePath = QLineEdit(self.verticalLayoutWidget_4)
        self.graphSavePath.setObjectName(u"graphSavePath")
        self.graphSavePath.setFont(font4)

        self.gridLayout_4.addWidget(self.graphSavePath, 0, 1, 1, 3)

        self.label_7 = QLabel(self.verticalLayoutWidget_4)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setFont(font4)

        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)

        self.label_10 = QLabel(self.verticalLayoutWidget_4)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setFont(font4)

        self.gridLayout_4.addWidget(self.label_10, 2, 0, 1, 1)

        self.label_8 = QLabel(self.verticalLayoutWidget_4)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setFont(font4)

        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)

        self.btn_settingsSave = QPushButton(self.verticalLayoutWidget_4)
        self.btn_settingsSave.setObjectName(u"btn_settingsSave")
        self.btn_settingsSave.setFont(font4)

        self.gridLayout_4.addWidget(self.btn_settingsSave, 5, 0, 1, 1)

        self.COMPathFC = QLineEdit(self.verticalLayoutWidget_4)
        self.COMPathFC.setObjectName(u"COMPathFC")
        self.COMPathFC.setFont(font4)

        self.gridLayout_4.addWidget(self.COMPathFC, 1, 1, 1, 2)

        self.btn_settingsDefault = QPushButton(self.verticalLayoutWidget_4)
        self.btn_settingsDefault.setObjectName(u"btn_settingsDefault")
        self.btn_settingsDefault.setFont(font4)

        self.gridLayout_4.addWidget(self.btn_settingsDefault, 6, 0, 1, 1)

        self.verticalSpacer_2 = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.gridLayout_4.addItem(self.verticalSpacer_2, 4, 0, 1, 1)

        self.COMPathESP = QLineEdit(self.verticalLayoutWidget_4)
        self.COMPathESP.setObjectName(u"COMPathESP")
        self.COMPathESP.setFont(font4)

        self.gridLayout_4.addWidget(self.COMPathESP, 2, 1, 1, 2)


        self.verticalLayout_3.addLayout(self.gridLayout_4)

        self.Screen.addWidget(self.Screen_Settings)
        self.Screen_Errors = QWidget()
        self.Screen_Errors.setObjectName(u"Screen_Errors")
        self.SubScreens_Errors = QStackedWidget(self.Screen_Errors)
        self.SubScreens_Errors.setObjectName(u"SubScreens_Errors")
        self.SubScreens_Errors.setGeometry(QRect(0, 0, 1024, 521))
        self.SubScreen_Errors_Basic = QWidget()
        self.SubScreen_Errors_Basic.setObjectName(u"SubScreen_Errors_Basic")
        self.verticalLayoutWidget = QWidget(self.SubScreen_Errors_Basic)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(0, 0, 1021, 521))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.title_Errors_basic = QLabel(self.verticalLayoutWidget)
        self.title_Errors_basic.setObjectName(u"title_Errors_basic")
        self.title_Errors_basic.setFont(font2)
        self.title_Errors_basic.setTextFormat(Qt.AutoText)
        self.title_Errors_basic.setScaledContents(False)
        self.title_Errors_basic.setWordWrap(False)
        self.title_Errors_basic.setIndent(-1)

        self.horizontalLayout_4.addWidget(self.title_Errors_basic)

        self.horizontalSpacer_2 = QSpacerItem(200, 1, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer_2)

        self.btn_Errors_InstanceHistory_basic = QPushButton(self.verticalLayoutWidget)
        self.btn_Errors_InstanceHistory_basic.setObjectName(u"btn_Errors_InstanceHistory_basic")
        sizePolicy2.setHeightForWidth(self.btn_Errors_InstanceHistory_basic.sizePolicy().hasHeightForWidth())
        self.btn_Errors_InstanceHistory_basic.setSizePolicy(sizePolicy2)
        self.btn_Errors_InstanceHistory_basic.setMinimumSize(QSize(300, 60))
        self.btn_Errors_InstanceHistory_basic.setMaximumSize(QSize(150, 60))
        font5 = QFont()
        font5.setFamilies([u"MS Shell Dlg 2"])
        font5.setPointSize(20)
        self.btn_Errors_InstanceHistory_basic.setFont(font5)
        self.btn_Errors_InstanceHistory_basic.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.btn_Errors_InstanceHistory_basic.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        icon19 = QIcon()
        icon19.addFile(u":/Errors/errors/current history.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Errors_InstanceHistory_basic.setIcon(icon19)
        self.btn_Errors_InstanceHistory_basic.setIconSize(QSize(48, 48))
        self.btn_Errors_InstanceHistory_basic.setCheckable(True)
        self.btn_Errors_InstanceHistory_basic.setChecked(True)
        self.btn_Errors_InstanceHistory_basic.setAutoExclusive(True)
        self.btn_Errors_InstanceHistory_basic.setFlat(True)

        self.horizontalLayout_4.addWidget(self.btn_Errors_InstanceHistory_basic)

        self.btn_Errors_AllHistory_basic = QPushButton(self.verticalLayoutWidget)
        self.btn_Errors_AllHistory_basic.setObjectName(u"btn_Errors_AllHistory_basic")
        sizePolicy2.setHeightForWidth(self.btn_Errors_AllHistory_basic.sizePolicy().hasHeightForWidth())
        self.btn_Errors_AllHistory_basic.setSizePolicy(sizePolicy2)
        self.btn_Errors_AllHistory_basic.setMinimumSize(QSize(300, 60))
        self.btn_Errors_AllHistory_basic.setMaximumSize(QSize(150, 60))
        self.btn_Errors_AllHistory_basic.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_Errors_AllHistory_basic.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        icon20 = QIcon()
        icon20.addFile(u":/Errors/errors/all history.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Errors_AllHistory_basic.setIcon(icon20)
        self.btn_Errors_AllHistory_basic.setIconSize(QSize(48, 48))
        self.btn_Errors_AllHistory_basic.setCheckable(True)
        self.btn_Errors_AllHistory_basic.setAutoExclusive(True)
        self.btn_Errors_AllHistory_basic.setFlat(True)

        self.horizontalLayout_4.addWidget(self.btn_Errors_AllHistory_basic)

        self.horizontalSpacer_3 = QSpacerItem(5, 5, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer_3)

        self.btn_Errors_Refresh_basic = QPushButton(self.verticalLayoutWidget)
        self.btn_Errors_Refresh_basic.setObjectName(u"btn_Errors_Refresh_basic")
        sizePolicy2.setHeightForWidth(self.btn_Errors_Refresh_basic.sizePolicy().hasHeightForWidth())
        self.btn_Errors_Refresh_basic.setSizePolicy(sizePolicy2)
        self.btn_Errors_Refresh_basic.setMinimumSize(QSize(50, 50))
        self.btn_Errors_Refresh_basic.setMaximumSize(QSize(50, 50))
        self.btn_Errors_Refresh_basic.setIcon(icon5)
        self.btn_Errors_Refresh_basic.setIconSize(QSize(48, 40))
        self.btn_Errors_Refresh_basic.setCheckable(True)
        self.btn_Errors_Refresh_basic.setAutoRepeat(True)
        self.btn_Errors_Refresh_basic.setFlat(False)

        self.horizontalLayout_4.addWidget(self.btn_Errors_Refresh_basic)


        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.terminal_basic = QTextEdit(self.verticalLayoutWidget)
        self.terminal_basic.setObjectName(u"terminal_basic")
        self.terminal_basic.viewport().setProperty(u"cursor", QCursor(Qt.CursorShape.SizeVerCursor))
        self.terminal_basic.setTabletTracking(True)
        self.terminal_basic.setAutoFillBackground(False)
        self.terminal_basic.setReadOnly(True)

        self.verticalLayout.addWidget(self.terminal_basic)

        self.SubScreens_Errors.addWidget(self.SubScreen_Errors_Basic)
        self.SubScreen_Errors_Admin = QWidget()
        self.SubScreen_Errors_Admin.setObjectName(u"SubScreen_Errors_Admin")
        sizePolicy2.setHeightForWidth(self.SubScreen_Errors_Admin.sizePolicy().hasHeightForWidth())
        self.SubScreen_Errors_Admin.setSizePolicy(sizePolicy2)
        self.SubScreen_Errors_Admin.setMinimumSize(QSize(1024, 525))
        self.SubScreen_Errors_Admin.setMaximumSize(QSize(1024, 525))
        self.verticalLayoutWidget_2 = QWidget(self.SubScreen_Errors_Admin)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(0, 0, 1021, 521))
        self.verticalLayout_2 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.title_Errors_admin = QLabel(self.verticalLayoutWidget_2)
        self.title_Errors_admin.setObjectName(u"title_Errors_admin")
        self.title_Errors_admin.setFont(font2)
        self.title_Errors_admin.setTextFormat(Qt.AutoText)
        self.title_Errors_admin.setScaledContents(False)
        self.title_Errors_admin.setWordWrap(False)
        self.title_Errors_admin.setIndent(-1)

        self.horizontalLayout_7.addWidget(self.title_Errors_admin)

        self.horizontalSpacer_5 = QSpacerItem(200, 1, QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_7.addItem(self.horizontalSpacer_5)

        self.btn_Errors_InstanceHistory_admin = QPushButton(self.verticalLayoutWidget_2)
        self.btn_Errors_InstanceHistory_admin.setObjectName(u"btn_Errors_InstanceHistory_admin")
        sizePolicy2.setHeightForWidth(self.btn_Errors_InstanceHistory_admin.sizePolicy().hasHeightForWidth())
        self.btn_Errors_InstanceHistory_admin.setSizePolicy(sizePolicy2)
        self.btn_Errors_InstanceHistory_admin.setMinimumSize(QSize(300, 60))
        self.btn_Errors_InstanceHistory_admin.setMaximumSize(QSize(150, 60))
        self.btn_Errors_InstanceHistory_admin.setFont(font5)
        self.btn_Errors_InstanceHistory_admin.setAutoFillBackground(False)
        self.btn_Errors_InstanceHistory_admin.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.btn_Errors_InstanceHistory_admin.setIcon(icon19)
        self.btn_Errors_InstanceHistory_admin.setIconSize(QSize(48, 48))
        self.btn_Errors_InstanceHistory_admin.setCheckable(True)
        self.btn_Errors_InstanceHistory_admin.setChecked(True)
        self.btn_Errors_InstanceHistory_admin.setFlat(True)

        self.horizontalLayout_7.addWidget(self.btn_Errors_InstanceHistory_admin)

        self.btn_Errors_AllHistory_admin = QPushButton(self.verticalLayoutWidget_2)
        self.btn_Errors_AllHistory_admin.setObjectName(u"btn_Errors_AllHistory_admin")
        sizePolicy2.setHeightForWidth(self.btn_Errors_AllHistory_admin.sizePolicy().hasHeightForWidth())
        self.btn_Errors_AllHistory_admin.setSizePolicy(sizePolicy2)
        self.btn_Errors_AllHistory_admin.setMinimumSize(QSize(300, 60))
        self.btn_Errors_AllHistory_admin.setMaximumSize(QSize(150, 60))
        self.btn_Errors_AllHistory_admin.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.btn_Errors_AllHistory_admin.setIcon(icon20)
        self.btn_Errors_AllHistory_admin.setIconSize(QSize(48, 48))
        self.btn_Errors_AllHistory_admin.setCheckable(True)
        self.btn_Errors_AllHistory_admin.setAutoExclusive(True)
        self.btn_Errors_AllHistory_admin.setFlat(True)

        self.horizontalLayout_7.addWidget(self.btn_Errors_AllHistory_admin)

        self.horizontalSpacer_6 = QSpacerItem(5, 1, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_7.addItem(self.horizontalSpacer_6)

        self.btn_Errors_Refresh_admin = QPushButton(self.verticalLayoutWidget_2)
        self.btn_Errors_Refresh_admin.setObjectName(u"btn_Errors_Refresh_admin")
        sizePolicy2.setHeightForWidth(self.btn_Errors_Refresh_admin.sizePolicy().hasHeightForWidth())
        self.btn_Errors_Refresh_admin.setSizePolicy(sizePolicy2)
        self.btn_Errors_Refresh_admin.setMinimumSize(QSize(50, 50))
        self.btn_Errors_Refresh_admin.setMaximumSize(QSize(50, 50))
        self.btn_Errors_Refresh_admin.setStyleSheet(u"")
        self.btn_Errors_Refresh_admin.setIcon(icon5)
        self.btn_Errors_Refresh_admin.setIconSize(QSize(40, 40))
        self.btn_Errors_Refresh_admin.setCheckable(True)
        self.btn_Errors_Refresh_admin.setAutoRepeat(True)
        self.btn_Errors_Refresh_admin.setAutoExclusive(False)
        self.btn_Errors_Refresh_admin.setFlat(True)

        self.horizontalLayout_7.addWidget(self.btn_Errors_Refresh_admin)


        self.verticalLayout_2.addLayout(self.horizontalLayout_7)

        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.terminal_typefield_admin = QLineEdit(self.verticalLayoutWidget_2)
        self.terminal_typefield_admin.setObjectName(u"terminal_typefield_admin")
        self.terminal_typefield_admin.setMinimumSize(QSize(0, 50))
        self.terminal_typefield_admin.setFont(font4)
        self.terminal_typefield_admin.setClearButtonEnabled(False)

        self.horizontalLayout_8.addWidget(self.terminal_typefield_admin)

        self.horizontalSpacer = QSpacerItem(5, 1, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_8.addItem(self.horizontalSpacer)

        self.btn_Errors_Send_admin = QPushButton(self.verticalLayoutWidget_2)
        self.btn_Errors_Send_admin.setObjectName(u"btn_Errors_Send_admin")
        sizePolicy2.setHeightForWidth(self.btn_Errors_Send_admin.sizePolicy().hasHeightForWidth())
        self.btn_Errors_Send_admin.setSizePolicy(sizePolicy2)
        self.btn_Errors_Send_admin.setMinimumSize(QSize(50, 50))
        self.btn_Errors_Send_admin.setMaximumSize(QSize(50, 50))
        self.btn_Errors_Send_admin.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_Errors_Send_admin.setAutoFillBackground(True)
        self.btn_Errors_Send_admin.setStyleSheet(u"")
        icon21 = QIcon()
        icon21.addFile(u":/Errors/errors/send.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_Errors_Send_admin.setIcon(icon21)
        self.btn_Errors_Send_admin.setIconSize(QSize(40, 40))
        self.btn_Errors_Send_admin.setFlat(True)

        self.horizontalLayout_8.addWidget(self.btn_Errors_Send_admin)


        self.verticalLayout_2.addLayout(self.horizontalLayout_8)

        self.terminal_admin = QTextEdit(self.verticalLayoutWidget_2)
        self.terminal_admin.setObjectName(u"terminal_admin")
        self.terminal_admin.viewport().setProperty(u"cursor", QCursor(Qt.CursorShape.SizeVerCursor))
        self.terminal_admin.setTabletTracking(True)
        self.terminal_admin.setAutoFillBackground(False)
        self.terminal_admin.setReadOnly(True)

        self.verticalLayout_2.addWidget(self.terminal_admin)

        self.SubScreens_Errors.addWidget(self.SubScreen_Errors_Admin)
        self.Screen.addWidget(self.Screen_Errors)

        self.horizontalLayout_2.addWidget(self.Screen)


        self.retranslateUi(Main)

        self.btn_Measure.setDefault(False)
        self.btn_Graphs.setDefault(False)
        self.btn_Settings.setDefault(False)
        self.btn_Errors.setDefault(False)
        self.Screen.setCurrentIndex(3)
        self.SubScreens_Errors.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Main)
    # setupUi

    def retranslateUi(self, Main):
        Main.setWindowTitle(QCoreApplication.translate("Main", u"Form", None))
        self.btn_Measure.setText("")
        self.btn_Graphs.setText("")
        self.btn_Settings.setText("")
        self.btn_Errors.setText("")
        self.logo_Polsl.setText("")
        self.logoMt.setText("")
        self.btn_StartMeasure.setText(QCoreApplication.translate("Main", u"Wykonaj Pomiar", None))
        self.btn_MeasureToGraph.setText(QCoreApplication.translate("Main", u"Przejd\u017a do poprzedniego Pomiaru", None))
        self.title_MeasureProgress_4.setText(QCoreApplication.translate("Main", u"Pomiary", None))
        self.btn_StopMeasure.setText(QCoreApplication.translate("Main", u"Zatrzymaj Proces", None))
        self.title_MeasureProgress_Step1.setText(QCoreApplication.translate("Main", u"Wykonywanie Pomiaru", None))
        self.text_MeasureProgress_Step1_1.setText(QCoreApplication.translate("Main", u"Zabezpieczenia zosta\u0142y zdj\u0119te.\n"
"Prosz\u0119 otworzy\u0107 komor\u0119 i\n"
" umie\u015bci\u0107 pr\u00f3bk\u0119 wewn\u0105trz.\n"
"\n"
"Po upewnieniu si\u0119 o poprawnym w\u0142o\u017ceniu pr\u00f3bki,\n"
" prosz\u0119 nacisn\u0105\u0107 przycisk obok by kontynuowa\u0107 proces.", None))
        self.btn_Measure_Step1_ObjectReady.setText("")
        self.text_MeasureProgress_Step1_2.setText(QCoreApplication.translate("Main", u"Gotowe", None))
        self.btn_Measure_Step1_Error_Errors.setText("")
        self.btn_Measure_Step1_Error_RefreshCOM.setText("")
        self.title_MeasureProgress_Step1_Error.setText(QCoreApplication.translate("Main", u"B\u0142\u0105d Po\u0142\u0105czenia", None))
        self.dsp_MeasureProgress_Step_1_1.setText("")
        self.dsp_MeasureProgress_Step_1_2.setText("")
        self.text_MeasureProgress_Step1_Error_2.setText(QCoreApplication.translate("Main", u"FC500", None))
        self.text_MeasureProgress_Step1_Error_3.setText(QCoreApplication.translate("Main", u"ESP", None))
        self.text_MeasureProgress_Step1_Error_1.setText(QCoreApplication.translate("Main", u"Sprawd\u017a po\u0142\u0105czenie u\u017c\u0105dzenia.", None))
        self.btn_Measure_Step2_LockSafety.setText("")
        self.dsp_MeasureProgress_Step_2_1.setText("")
        self.title_MeasureProgress_Step2.setText(QCoreApplication.translate("Main", u"Przygotowanie do Pomiaru", None))
        self.text_MeasureProgress_Step1_5.setText(QCoreApplication.translate("Main", u"Umie\u015b\u0107 pr\u00f3bk\u0119 w komorze.\n"
"Nast\u0119pnie po zamkni\u0119ciu drzwi zablokuj je.\n"
"Poczekaj na wst\u0119pne napi\u0119cie pr\u00f3bki.", None))
        self.title_MeasureProgress_Step2_Error.setText(QCoreApplication.translate("Main", u"B\u0142\u0105d Przygotowania", None))
        self.btn_Measure_Step2_Error_LockSafety.setText("")
        self.btn_Measure_Step2_Error_Retry.setText("")
        self.text_MeasureProgress_Step2_Error_1.setText(QCoreApplication.translate("Main", u"Nast\u0105pi\u0142 b\u0142\u0105d podczas przygotowania pr\u00f3bki.\n"
"Program nie wykry\u0142 jej obecno\u015bci.\n"
"Prosz\u0119 ponownie j\u0105 ustawi\u0107.\n"
"W przypadku gdy pr\u00f3bka jest poprawnie u\u0142o\u017cona,\n"
" mo\u017cna spr\u00f3bowa\u0107 jeszcze raz.", None))
        self.dsp_MeasureProgress_Step_2_Error_1.setText("")
        self.title_MeasureProgress_Step2_Reset.setText(QCoreApplication.translate("Main", u"Zabezpieczenie zdj\u0119te.", None))
        self.text_MeasureProgress_Step2_Error_2.setText(QCoreApplication.translate("Main", u"Prosz\u0119 poprawi\u0107 pr\u00f3bk\u0119.\n"
"Nast\u0119pnie prosz\u0119 zamkn\u0105\u0107 drzwi i\n"
"nacisn\u0105\u0107 przycisk", None))
        self.btn_Measure_Step2_LockSafety_2.setText("")
        self.title_MeasureProgress_Step2_Reset_2.setText(QCoreApplication.translate("Main", u"Pomiar rozpocz\u0119ty", None))
        self.btn_Measure_Step3.setText("")
        self.title_MeasureProgress_Step2_Reset_3.setText(QCoreApplication.translate("Main", u"Pomiar zako\u0144czony", None))
        self.dsp_MeasureProgress_Step_1.setText("")
        self.dsp_MeasureProgress_Step_2.setText("")
        self.dsp_MeasureProgress_Step_3.setText("")
        self.dsp_MeasureProgress_Step_4.setText("")
        self.title_Graphs.setText(QCoreApplication.translate("Main", u"Wykresy", None))
        self.btn_Graph_right.setText("")
        self.btn_Graph_zout.setText("")
        self.btn_Graph_up.setText("")
        self.btn_Graph_left.setText("")
        self.btn_Graph_down.setText("")
        self.btn_Graph_zin.setText("")
        self.btn_SaveGraph.setText("")
        self.btn_LoadGraph.setText("")
        self.btn_Graph_resetview.setText("")
        self.title_Settings.setText(QCoreApplication.translate("Main", u"Ustawienia", None))
        self.devMode.setText(QCoreApplication.translate("Main", u"Tryb deweloperski", None))
        self.label_7.setText(QCoreApplication.translate("Main", u"\u015acie\u017cka do zapisu wykres\u00f3w", None))
        self.label_10.setText(QCoreApplication.translate("Main", u"Port COM mikrokontrolera", None))
        self.label_8.setText(QCoreApplication.translate("Main", u"Port COM si\u0142omierza", None))
        self.btn_settingsSave.setText(QCoreApplication.translate("Main", u"Zapisz ustawienia", None))
        self.btn_settingsDefault.setText(QCoreApplication.translate("Main", u"Przywr\u00f3\u0107 domy\u015blne ustawienia", None))
        self.title_Errors_basic.setText(QCoreApplication.translate("Main", u"B\u0142\u0119dy", None))
        self.btn_Errors_InstanceHistory_basic.setText("")
        self.btn_Errors_AllHistory_basic.setText("")
        self.btn_Errors_Refresh_basic.setText("")
        self.terminal_basic.setPlaceholderText("")
        self.title_Errors_admin.setText(QCoreApplication.translate("Main", u"Terminal", None))
        self.btn_Errors_InstanceHistory_admin.setText("")
        self.btn_Errors_AllHistory_admin.setText("")
        self.btn_Errors_Refresh_admin.setText("")
        self.btn_Errors_Send_admin.setText("")
        self.terminal_admin.setPlaceholderText("")
    # retranslateUi

