# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'v27HyFDcV.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *

import IconResource_rc

class Ui_Main(object):
    def setupUi(self, Main):
        if Main.objectName():
            Main.setObjectName(u"Main")
        Main.resize(1024, 600)
        Main.setMinimumSize(QSize(1024, 600))
        Main.setMaximumSize(QSize(1024, 600))
        Main.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.centralwidget = QWidget(Main)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.Menu = QFrame(self.centralwidget)
        self.Menu.setObjectName(u"Menu")
        self.Menu.setMinimumSize(QSize(0, 75))
        self.Menu.setMaximumSize(QSize(16777215, 75))
        self.Menu.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0.0113636 rgba(225, 225, 225, 255), stop:1 rgba(245, 245, 245, 255));")
        self.Menu.setFrameShape(QFrame.NoFrame)
        self.Menu.setFrameShadow(QFrame.Raised)
        self.horizontalLayoutWidget = QWidget(self.Menu)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(0, 0, 1031, 81))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(20, 5, 20, 10)
        self.btn_Measure = QPushButton(self.horizontalLayoutWidget)
        self.btn_Measure.setObjectName(u"btn_Measure")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Measure.sizePolicy().hasHeightForWidth())
        self.btn_Measure.setSizePolicy(sizePolicy)
        self.btn_Measure.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_Measure.setAcceptDrops(False)
        self.btn_Measure.setAutoFillBackground(False)
        self.btn_Measure.setStyleSheet(u"border-bottom-color: rgb(255, 85, 0);")
        icon = QIcon()
        icon.addFile(u":/Menu/menu/Measure.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_Measure.setIcon(icon)
        self.btn_Measure.setIconSize(QSize(48, 48))
        self.btn_Measure.setCheckable(False)
        self.btn_Measure.setChecked(False)
        self.btn_Measure.setAutoRepeat(False)
        self.btn_Measure.setAutoExclusive(False)
        self.btn_Measure.setAutoDefault(False)
        self.btn_Measure.setFlat(True)

        self.horizontalLayout.addWidget(self.btn_Measure)

        self.btn_Graphs = QPushButton(self.horizontalLayoutWidget)
        self.btn_Graphs.setObjectName(u"btn_Graphs")
        sizePolicy.setHeightForWidth(self.btn_Graphs.sizePolicy().hasHeightForWidth())
        self.btn_Graphs.setSizePolicy(sizePolicy)
        self.btn_Graphs.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_Graphs.setAcceptDrops(False)
        self.btn_Graphs.setAutoFillBackground(False)
        self.btn_Graphs.setStyleSheet(u"border-bottom-color: rgb(255, 85, 0);")
        icon1 = QIcon()
        icon1.addFile(u":/Menu/menu/Graph.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_Graphs.setIcon(icon1)
        self.btn_Graphs.setIconSize(QSize(48, 48))
        self.btn_Graphs.setCheckable(False)
        self.btn_Graphs.setChecked(False)
        self.btn_Graphs.setAutoRepeat(False)
        self.btn_Graphs.setAutoExclusive(False)
        self.btn_Graphs.setAutoDefault(False)
        self.btn_Graphs.setFlat(True)

        self.horizontalLayout.addWidget(self.btn_Graphs)

        self.btn_Settings = QPushButton(self.horizontalLayoutWidget)
        self.btn_Settings.setObjectName(u"btn_Settings")
        sizePolicy.setHeightForWidth(self.btn_Settings.sizePolicy().hasHeightForWidth())
        self.btn_Settings.setSizePolicy(sizePolicy)
        self.btn_Settings.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_Settings.setAcceptDrops(False)
        self.btn_Settings.setAutoFillBackground(False)
        self.btn_Settings.setStyleSheet(u"border-bottom-color: rgb(255, 85, 0);")
        icon2 = QIcon()
        icon2.addFile(u":/Menu/menu/Settings.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_Settings.setIcon(icon2)
        self.btn_Settings.setIconSize(QSize(48, 48))
        self.btn_Settings.setCheckable(False)
        self.btn_Settings.setChecked(False)
        self.btn_Settings.setAutoRepeat(False)
        self.btn_Settings.setAutoExclusive(False)
        self.btn_Settings.setAutoDefault(False)
        self.btn_Settings.setFlat(True)

        self.horizontalLayout.addWidget(self.btn_Settings)

        self.btn_Errors = QPushButton(self.horizontalLayoutWidget)
        self.btn_Errors.setObjectName(u"btn_Errors")
        sizePolicy.setHeightForWidth(self.btn_Errors.sizePolicy().hasHeightForWidth())
        self.btn_Errors.setSizePolicy(sizePolicy)
        self.btn_Errors.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_Errors.setAcceptDrops(False)
        self.btn_Errors.setAutoFillBackground(False)
        self.btn_Errors.setStyleSheet(u"border-bottom-color: rgb(255, 85, 0);")
        icon3 = QIcon()
        icon3.addFile(u":/Menu/menu/Error.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_Errors.setIcon(icon3)
        self.btn_Errors.setIconSize(QSize(48, 48))
        self.btn_Errors.setCheckable(False)
        self.btn_Errors.setChecked(False)
        self.btn_Errors.setAutoRepeat(False)
        self.btn_Errors.setAutoExclusive(False)
        self.btn_Errors.setAutoDefault(False)
        self.btn_Errors.setFlat(True)

        self.horizontalLayout.addWidget(self.btn_Errors)


        self.verticalLayout.addWidget(self.Menu)

        self.Content = QFrame(self.centralwidget)
        self.Content.setObjectName(u"Content")
        font = QFont()
        font.setFamily(u"Futura Std Book")
        self.Content.setFont(font)
        self.Content.setStyleSheet(u"")
        self.Content.setFrameShape(QFrame.NoFrame)
        self.Content.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.Content)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.Screen = QStackedWidget(self.Content)
        self.Screen.setObjectName(u"Screen")
        self.Screen_MeasureMain = QWidget()
        self.Screen_MeasureMain.setObjectName(u"Screen_MeasureMain")
        self.title_MeasureMain = QLabel(self.Screen_MeasureMain)
        self.title_MeasureMain.setObjectName(u"title_MeasureMain")
        self.title_MeasureMain.setGeometry(QRect(50, 30, 181, 71))
        font1 = QFont()
        font1.setFamily(u"Futura Std Book")
        font1.setPointSize(36)
        self.title_MeasureMain.setFont(font1)
        self.title_MeasureMain.setTextFormat(Qt.AutoText)
        self.title_MeasureMain.setScaledContents(False)
        self.title_MeasureMain.setWordWrap(False)
        self.title_MeasureMain.setIndent(-1)
        self.btn_StartMeasure = QPushButton(self.Screen_MeasureMain)
        self.btn_StartMeasure.setObjectName(u"btn_StartMeasure")
        self.btn_StartMeasure.setGeometry(QRect(360, 210, 281, 91))
        font2 = QFont()
        font2.setFamily(u"Futura Std Book")
        font2.setPointSize(24)
        self.btn_StartMeasure.setFont(font2)
        self.btn_StartMeasure.setStyleSheet(u"background-color: rgb(191, 191, 191);")
        self.btn_MeasureToGraph = QPushButton(self.Screen_MeasureMain)
        self.btn_MeasureToGraph.setObjectName(u"btn_MeasureToGraph")
        self.btn_MeasureToGraph.setGeometry(QRect(250, 320, 531, 91))
        self.btn_MeasureToGraph.setFont(font2)
        self.btn_MeasureToGraph.setAutoFillBackground(False)
        self.btn_MeasureToGraph.setStyleSheet(u"background-color: rgb(191, 191, 191);")
        self.btn_MeasureToGraph.setAutoRepeat(False)
        self.Screen.addWidget(self.Screen_MeasureMain)
        self.Screen_MeasureProgress = QWidget()
        self.Screen_MeasureProgress.setObjectName(u"Screen_MeasureProgress")
        self.title_MeasureProgress = QLabel(self.Screen_MeasureProgress)
        self.title_MeasureProgress.setObjectName(u"title_MeasureProgress")
        self.title_MeasureProgress.setGeometry(QRect(70, 50, 491, 71))
        self.title_MeasureProgress.setFont(font1)
        self.title_MeasureProgress.setTextFormat(Qt.AutoText)
        self.title_MeasureProgress.setScaledContents(False)
        self.title_MeasureProgress.setWordWrap(False)
        self.title_MeasureProgress.setIndent(-1)
        self.progressBar = QProgressBar(self.Screen_MeasureProgress)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(40, 140, 921, 16))
        font3 = QFont()
        font3.setFamily(u"Arial")
        self.progressBar.setFont(font3)
        self.progressBar.setValue(24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.btn_StopMeasure = QPushButton(self.Screen_MeasureProgress)
        self.btn_StopMeasure.setObjectName(u"btn_StopMeasure")
        self.btn_StopMeasure.setGeometry(QRect(680, 190, 281, 91))
        self.btn_StopMeasure.setFont(font2)
        self.btn_StopMeasure.setStyleSheet(u"background-color: rgb(191, 191, 191);")
        self.Screen.addWidget(self.Screen_MeasureProgress)
        self.Screen_Graphs = QWidget()
        self.Screen_Graphs.setObjectName(u"Screen_Graphs")
        self.title_Graphs = QLabel(self.Screen_Graphs)
        self.title_Graphs.setObjectName(u"title_Graphs")
        self.title_Graphs.setGeometry(QRect(60, 40, 491, 71))
        self.title_Graphs.setFont(font1)
        self.title_Graphs.setTextFormat(Qt.AutoText)
        self.title_Graphs.setScaledContents(False)
        self.title_Graphs.setWordWrap(False)
        self.title_Graphs.setIndent(-1)
        self.Screen.addWidget(self.Screen_Graphs)
        self.Screen_Settings = QWidget()
        self.Screen_Settings.setObjectName(u"Screen_Settings")
        self.title_Settings = QLabel(self.Screen_Settings)
        self.title_Settings.setObjectName(u"title_Settings")
        self.title_Settings.setGeometry(QRect(100, 50, 491, 71))
        self.title_Settings.setFont(font1)
        self.title_Settings.setTextFormat(Qt.AutoText)
        self.title_Settings.setScaledContents(False)
        self.title_Settings.setWordWrap(False)
        self.title_Settings.setIndent(-1)
        self.Screen.addWidget(self.Screen_Settings)
        self.Screen_Errors = QWidget()
        self.Screen_Errors.setObjectName(u"Screen_Errors")
        self.title_Errors = QLabel(self.Screen_Errors)
        self.title_Errors.setObjectName(u"title_Errors")
        self.title_Errors.setGeometry(QRect(60, 50, 491, 71))
        self.title_Errors.setFont(font1)
        self.title_Errors.setTextFormat(Qt.AutoText)
        self.title_Errors.setScaledContents(False)
        self.title_Errors.setWordWrap(False)
        self.title_Errors.setIndent(-1)
        self.Screen.addWidget(self.Screen_Errors)

        self.horizontalLayout_2.addWidget(self.Screen)


        self.verticalLayout.addWidget(self.Content)

        Main.setCentralWidget(self.centralwidget)

        self.retranslateUi(Main)

        self.btn_Measure.setDefault(False)
        self.btn_Graphs.setDefault(False)
        self.btn_Settings.setDefault(False)
        self.btn_Errors.setDefault(False)
        self.Screen.setCurrentIndex(4)


        QMetaObject.connectSlotsByName(Main)
    # setupUi

    def retranslateUi(self, Main):
        Main.setWindowTitle(QCoreApplication.translate("Main", u"MainWindow", None))
        self.btn_Measure.setText("")
        self.btn_Graphs.setText("")
        self.btn_Settings.setText("")
        self.btn_Errors.setText("")
        self.title_MeasureMain.setText(QCoreApplication.translate("Main", u"Pomiary", None))
        self.btn_StartMeasure.setText(QCoreApplication.translate("Main", u"Wykonaj Pomiar", None))
        self.btn_MeasureToGraph.setText(QCoreApplication.translate("Main", u"Przejd\u017a do poprzedniego Pomiaru", None))
        self.title_MeasureProgress.setText(QCoreApplication.translate("Main", u"Wykonywanie Pomiaru", None))
        self.btn_StopMeasure.setText(QCoreApplication.translate("Main", u"Zatrzymaj", None))
        self.title_Graphs.setText(QCoreApplication.translate("Main", u"Wykresy", None))
        self.title_Settings.setText(QCoreApplication.translate("Main", u"Ustawienia", None))
        self.title_Errors.setText(QCoreApplication.translate("Main", u"B\u0142\u0119dy", None))
    # retranslateUi

